input.file=Agenda_DataEntry.vm
output.file=Agenda_DataEntry.java
output.dir=C:\\plucien\\[PERSONNEL]\\agenda
fieldNames=[]Version;Deleted;Nombre;Apellido;Direccion;Sexo;Pais;Telefono1;Telefono2;Telefono3;Email;Marca;FechaActualizacion;FechaCreacion;Listar;Notas
#Dia;Mes;Ano;Imagen;
