#Configuracion de DirectorySynchronizer
#
DirectorySynchronizer.prompt=Introduzca los directorios a sincronizar.
DirectorySynchronizer.selectTargetsButton.text=Select targets
DirectorySynchronizer.selectFileButton.text=Select target file
DirectorySynchronizer.clearButton.text=Clear display
DirectorySynchronizer.clearAllButton.text=Clear display and counters
DirectorySynchronizer.cleanupButton.text=Clean up unwanted files
DirectorySynchronizer.exitButton.text=That's all folks!
DirectorySynchronizer.maxHistory=10
DirectorySynchronizer.OK=Date con furia
DirectorySynchronizer.KO=Ni de vaina
DirectorySynchronizer.status.msg=Dirs created = %d, files created = %d, files updated = %d, files with same content = %d, files not modified = %d