#Configuracion de DirectorySynchronizer
#Tue Aug 07 11:57:45 CEST 2018
DirectorySynchronizer.item.4=E\:\\quarantine_projects\\Alles\\src|C\:\\home\\development\\modules\\src
DirectorySynchronizer.item.3=C\:\\home\\development\\quarantine_projects|E\:\\quarantine_projects
DirectorySynchronizer.item.2=C\:\\m2_repository|E\:\\m2_repository
DirectorySynchronizer.item.1=C\:\\quickenw\\qdata\\|L\:\\quickenw\\qdata\\
DirectorySynchronizer.item.0=E\:\\quarantine_projects\\Alles\\src\\java\\org\\pclg\\filesystem|C\:\\home\\development\\modules\\src\\java\\org\\pclg\\filesystem
