#Configuracion de DirectorySynchronizer
# suppress inspection "UnusedProperty" for whole file
#
Application.ClassPath=derby.jar
#
#Specific to ACME
# FIXME: este formateo parece indicar que son grupos, y no lo son
DirectorySynchronizer.cleanup.baseDirs=\
  |/home/pablo/Finance|/media/pablo/MERCURIO/home/pablo/Finance|/media/pablo/Fatman/home/pablo/Finance|/media/pablo/LOKI-II/home/pablo/Finance\
  |/home/pablo/quickenw/qdata|/media/pablo/Fatman/home/pablo/quickenw/qdata|/media/pablo/LOKI-II/home/pablo/quickenw/qdata\
  |/home/pablo/m2_repository|/media/pablo/MERCURIO/m2_repository\
  |/home/pablo/development/dist|/media/pablo/MERCURIO/bin|/media/pablo/LOKI-II/bin\|/media/pablo/Fatman/bin
  |/home/pablo/development/projects/Alles|/media/pablo/MERCURIO/home/pablo/development/projects/Alles\
  |/media/pablo/MERCURIO/quarantine_projects|/home/pablo/development/quarantine_projects\
  |/media/pablo/MERCURIO/home/pablo/img/fotos|/media/pablo/Fatman/home/pablo/img/fotos|/home/pablo/img/fotos\
  |/media/pablo/MERCURIO/home/pablo/development/projects|/media/pablo/Fatman/home/pablo/development/projects|/media/pablo/LOKI-II/home/pablo/development/projects|/home/pablo/development/projects

#Substitution variables. Use forward slash (/) instead of escaped backwards
USER_PROFILE_DIR=/home/pablo
LOCAL_M2_REPOSITORY_DIR=/home/m2_repository
ROOT_C=/
ROOT_E=/media/pablo/MERCURIO
ROOT_F=/media/pablo/Fatman
ROOT_G=/media/pablo/FD71-883A
ROOT_H=/media/pablo/3F46-07E3
ROOT_L=/media/pablo/LOKI-II

DirectorySynchronizer.showKaleidoscope=false
