#Configuracion de DirectorySynchronizer
#
DirectorySynchronizer.cleanup.baseDirs=C:\\devops\\workspace|E:\\workspace_EBU|F:\\bin|E:\\bin|C:\\plucien\\bin|C:\\devops\\work\\repo|E:\\m2_repository

#Substitution variables. Use forward slash (/) instead of escaped backwards
USER_PROFILE_DIR=C:/Users/pacelucien/

showKaleidoscope=false