<project name="pclg-compdel" default="build" basedir="../../../..">

    <description>Builds pclg compdel</description>

    <property name="module_pclg_compdel" location="${basedir}/pclg-compdel"/>
    <property file="${basedir}/local_config.properties"/>

    <property name="src" location="${module_pclg_compdel}/src/main/java"/>
    <property name="lib_dir" value="${basedir}/../lib"/>
    <property name="libLAF_dir" value="${basedir}/../lib_L&amp;F"/>
    <property name="build" location="${basedir}/../../build/compdel"/>
    <property name="dist" location="${basedir}/../../dist"/>
    <property name="pclg-compdel_jar_name" value="pclg-compdel.jar"/>
    <property name="classpath" value="
        ${lib_dir}/log4j-1.2-api-2.13.3.jar:
        ${lib_dir}/log4j-api-2.13.3.jar:
        ${lib_dir}/log4j-core-2.13.3.jar:

        ${dist}/pclg-tools.jar:
        "/>

    <target name="_init">
        <tstamp/>
        <mkdir dir="${build}"/>
        <mkdir dir="${dist}"/>
    </target>

    <target name="_compile" depends="_init" description="Compile the sources">
        <javac
                classpath="${classpath}"
                modulepath="${classpath}"
                includeantruntime="false"
                srcdir="${src}"
                destdir="${build}"
                deprecation="on"
                debug="true"
                verbose="no"
                listfiles="yes"
                source="${local_config.jdk-version}"
                target="${local_config.jdk-version}"
                encoding="ISO-8859-1">
            <compilerarg value="-Xlint"/>
        </javac>
    </target>

    <target name="pclg-compdel_jar" depends="_compile">
        <jar destfile="${dist}/${pclg-compdel_jar_name}" basedir="${build}" excludes="**">
            <fileset dir="${build}" includes="**/*.class"/>
            <manifest>
                <attribute name="Built-By" value="${user.name}"/>
                <attribute name="Main-Class" value="org.pclg.compdel.CompDel"/>
                <attribute name="Class-Path" value="pclg-tools.jar : Icons.jar : toolbarButtonGraphics.jar : log4j-api-2.13.3.jar : log4j-core-2.13.3.jar"/>
            </manifest>
        </jar>
    </target>

    <target name="build" depends="pclg-compdel_jar"/>

     <target name="clean">
         <echo message="Cleaning ${ant.project.name}"/>
         <delete includeEmptyDirs="true">
             <fileset dir="${build}" includes="*/**"/>
         </delete>
    </target>
</project>