input.file=NavigationtProxy.vm
output.file=NavigationtProxy.java
output.dir=D:\\projects\\prj-ulisng-refonte2\\workspace\\ULISNG-MODULES\\src\\main\\java
domain=PL
fonction=PLELI002
description=AccederEDLDSE
#params=[]par1;par2;par3
#variables=[]$$mg_socdef;$$mg_actdef;$$gen_push;$$gen_navval1
variables=[]$$gen_navval1;$$paesi_num
author=PLU
