#Configuracion de net.asintec.migrator.Migrator
#Sat Nov 26 17:31:39 CET 2005
bounds.h=696
bounds.w=707
bounds.x=313
bounds.y=3
debugLevel=2
errorsBounds.h=336
errorsBounds.w=997
errorsBounds.x=1
errorsBounds.y=364
errorsVisible=true
lafName=com.incors.plaf.kunststoff.KunststoffLookAndFeel
lafThemeName=org.pclg.gui.temas.MonoTheme
lastConfigurationFile=C\:\\pablo\\java\\_dist\\Directorios.conf
outputBounds.h=351
outputBounds.w=307
outputBounds.x=0
outputBounds.y=6
outputVisible=true
probandoOracle=false
