driver.name=org.apache.derby.jdbc.EmbeddedDriver
db.url=jdbc:derby:C:/tmp/Vox;create=true;collation=TERRITORY_BASED:PRIMARY;
userID=pepito
passwd=secreto
button.init=Inicializar DB
button.fwd=>>>
button.bck=<<<
button.add=+
button.dudosas=Mover a dudosas
button.sinonimos=Sinónimos
textfile.path=C:/home/development/modules/resources/dictionary/Varios - Diccionario Basico Español de 5.000 entradas.txt
icon.path=C:/home/development/modules/resources/dictionary/dictionary.jpg
animated.icon.path=C:/home/development/modules/resources/dictionary/Check1.gif
sinonymfile.path=C:/home/development/modules/resources/dictionary/Sinónimos.txt