##La lista, separada por '|' de los archivos o directorios a agregar al
#classpath the la aplicaci�n.
Application.ClassPath=C:/home/development/projects/lib/derby.jar|C:/home/development/projects/lib/derbyclient.jar|C:/home/development/projects/lib/ez-vcard-0.9.5.jar|C:/home/development/projects/lib/lib_L&F

#Set this if a language is to be used independently of the computer setings
Application.ForceLanguage=DE

#Are Fortunes enabled at startup?
Agenda.FortunesAtStartup=true

#Are Interesting Dates enabled at startup?
Agenda.InterestingDatesAtStartup=true

Agenda.show.SplashWindow=true

# Look and Feel
Agenda.L&F=com.incors.plaf.kunststoff.KunststoffLookAndFeel

# los d�as antes y despues de hoy que se listan para los cumplea�os cercanos
AgendaDb.daysFork4Birthdays=7

# los d�as antes y despues de hoy que se listan las fechas "interesantes"
AgendaDb.daysFork4InterestingDates=10

# Los d�as "interesantes deben ser divisibles por este:
AgendaDb.interestingDatesDivisor=500

# los d�as previos a la �ltima modificacion (0 == 1) :).
AgendaDb.daysFork4RecentlyModified=1

# M�xima cantidad de backups a conservar cada vez que se hace una copia de la db.
AgendaDb.maxBackupHistory=5

# El pa�s a seleccionar por defecto al crear nuevos registros.
Agenda.default.country=34

# Root filesystem where the images are stored
Agenda.images.root=C:/

#Configuaci�n para Derby
AgendaDb.className=org.pclg.agenda.jdbc.AgendaDbJDBC
AgendaDb.driver=org.apache.derby.jdbc.EmbeddedDriver
AgendaDb.path=/_Agenda/agendaDB
AgendaDb.url=jdbc:derby:[[[PATH]]];create=true;collation=TERRITORY_BASED:PRIMARY;dataEncryption=true;bootPassword=[[[PWD]]]
AgendaDb.shutdown.url=jdbc:derby:[[[PATH]]];shutdown=true
#AgendaDb.driver=org.apache.derby.jdbc.ClientDriver
#AgendaDb.url=jdbc:derby://localhost:1527/C:/_Agenda/agendaDB;create=true;collation=TERRITORY_BASED:PRIMARY;dataEncryption=true;bootPassword=[[[PWD]]]
#AgendaDb.url=jdbc:derby://localhost:1527/memory:agendaDB;create=true;collation=TERRITORY_BASED:PRIMARY;dataEncryption=true;bootPassword=[[[PWD]]]

AgendaDb.secondary.className=org.pclg.agenda.jdbc.AgendaDbJDBC
AgendaDb.secondary.driver=org.apache.derby.jdbc.EmbeddedDriver
AgendaDb.secondary.path=L:/_Agenda/agendaDB
AgendaDb.secondary.url=jdbc:derby:[[[PATH]]];create=false;dataEncryption=true;bootPassword=[[[PWD]]]
AgendaDb.secondary.shutdown.url=jdbc:derby:[[[PATH]]];shutdown=true

# Indica que debemos crear las tablas 'from scratch' aunque ya existan.
# Esto es muy peligroso !!!!!!
AgendaDb.createTables=false
