<project name="pclg-agenda" default="build" basedir="../../../..">

    <description>Builds pclg agenda</description>

    <property name="module" location="${basedir}/${ant.project.name}"/>
    <property file="${basedir}/local_config.properties"/>

    <property name="src" location="${module}/src/main/java"/>
    <property name="resources" location="${module}/src/main/resources"/>
    <property name="lib_dir" value="${basedir}/../lib"/>
    <property name="build" location="${basedir}/../../build/${ant.project.name}"/>
    <property name="dist" location="${basedir}/../../dist"/>
    <property name="module_jar" value="${ant.project.name}.jar"/>

    <property name="properties" value="Agenda*.properties"/>

    <property name="classpath" value="
        ${lib_dir}/log4j-1.2-api-2.17.2.jar:
        ${lib_dir}/log4j-api-2.17.2.jar:
        ${lib_dir}/log4j-core-2.17.2.jar:

        ${lib_dir}/jakarta.activation-api-2.0.0-RC3.jar:
        ${lib_dir}/jakarta.xml.bind-api-2.3.3.jar:
        ${lib_dir}/ez-vcard-0.9.5.jar:
        ${lib_dir}/jpatterns-0.1.jar:
        ${dist}/pclg-tools.jar:
    "/>

    <!--    Tests-->
    <property name="tests_dir" value="${module}/src/test"/>
    <property name="build_tests" location="${basedir}/../../build/${ant.project.name}_tests"/>
    <property name="test_resources" location="${module}/src/test/resources"/>
    <property name="build.test.results.dir" value="/tmp/test_results"/>
    <taskdef resource="testngtasks" classpath="${lib_dir}/testng-6.8.8.jar"/>
    <property name="test_classpath" value="
        ${lib_dir}/testng-6.8.8.jar:
        ${lib_dir}/jcommander-1.27.jar:
    "/>

    <target name="_init">
        <tstamp/>
        <mkdir dir="${build}"/>
        <mkdir dir="${dist}"/>
        <mkdir dir="${build_tests}"/>

        <copy todir="${build}" preservelastmodified="true">
            <fileset dir="${resources}" includes="${properties}"/>
        </copy>

        <copy todir="${dist}" preservelastmodified="true">
            <fileset dir="${resources}" includes="${properties}"/>
        </copy>

        <copy file="${resources}/Agenda_technical-${local_config.host.name}.properties" tofile="${build}/Agenda_technical.properties" preservelastmodified="true"/>
        <copy file="${resources}/Agenda_technical-${local_config.host.name}.properties" tofile="${dist}/Agenda_technical.properties" preservelastmodified="true"/>
    </target>

    <target name="_compile" depends="_init" description="Compile the sources">
        <javac
                modulepath="${classpath}"
                includeantruntime="false"
                srcdir="${src}"
                destdir="${build}"
                deprecation="on"
                debug="true"
                verbose="no"
                listfiles="yes"
                source="${local_config.jdk-version}"
                target="${local_config.jdk-version}"
                encoding="ISO-8859-1">
            <compilerarg value="-Xlint"/>
        </javac>
    </target>

    <target name="_compile_tests" depends="_compile"
            description="compile the tests ">
        <javac
                classpath="${test_classpath} : ${classpath} : ${build}"
                includeantruntime="false"
                srcdir="${tests_dir}"
                destdir="${build_tests}"
                deprecation="on"
                debug="true"
                verbose="no"
                listfiles="yes"
                source="${local_config.jdk-version}"
                target="${local_config.jdk-version}"
                encoding="ISO-8859-1">
            <compilerarg value="-Xlint"/>
        </javac>
    </target>

    <target name="_tests" depends="_compile_tests">
        <testng failureProperty="test.failed" dumpCommand="true" outputdir="${build.test.results.dir}">
            <classpath>
                <path path="${test_resources} : ${test_classpath} : ${classpath} : ${build} : ${dist}"/>
            </classpath>
            <classpath location="${build_tests}"/>
            <classpath location="${tests_dir}"/>

            <classfileset dir="${build_tests}" includes="**/*Test*.class"/>

        </testng>
        <fail message="Test failure detected, check test results." if="test.failed"/>
    </target>

    <target name="module_jar" depends="_compile">
        <jar destfile="${dist}/${module_jar}" basedir="${build}" excludes="**">
            <fileset dir="${build}" includes="**/*.class"/>
            <manifest>
                <attribute name="Built-By" value="${user.name}"/>
                <attribute name="Main-Class" value="org.pclg.agenda.Agenda"/>
                <attribute name="Class-Path" value="pclg-tools.jar : Icons.jar : Sounds.jar : toolbarButtonGraphics.jar : log4j-api-2.17.2.jar : log4j-core-2.17.2.jar : derby.jar : javaee.jar : ez-vcard-0.9.5.jar : lib_L&amp;F/kunststoff.jar : ."/>
            </manifest>
        </jar>
    </target>

    <target name="build" depends="_tests, module_jar"/>

     <target name="clean">
         <echo message="Cleaning ${ant.project.name}"/>
         <delete includeEmptyDirs="true">
             <fileset dir="${build}" includes="*/**"/>
         </delete>
         <delete includeEmptyDirs="true">
             <fileset dir="${build_tests}" includes="*/**"/>
         </delete>
    </target>
</project>