/pablo/java/_src/gui.mdl
/pablo/java/_src/console_con_properties.mdl
/pablo/java/_src/console_sin_properties.mdl
/pablo/java/_src/interface.mdl
/pablo/java/_src/bean.mdl
/pablo/java/_src/graphic_bean.mdl
