#Tamaño del pool de threads
poolSize=10

charset.name=ISO-8859-1

#Indica si los archivos se sobreescriben con caracteres estocásticos antes de borrarlos
#true or false
overwrite=false

#The levels in descending order are:
#
#OFF
#SEVERE (highest value)
#WARNING
#INFO
#CONFIG
#FINE
#FINER
#FINEST (lowest value)
#ALL
level=CONFIG
file=C:/tmp/Clean.log