// ******************************** package
package org.pclg.tools;

// ******************************** imports
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.util.Arrays;
import java.util.Date;
import java.util.Properties;

import static org.pclg.tools.StringTools.EMPTY_STRING_ARRAY;

/**
	SortedProperties <BR>
	Tiene la misma funcionalidad que Properties, pero se almacena en orden alfabético
	@author El Coyote Cojo
	@version 2002.may.07 13:06:17, CEST
*/
public class SortedProperties extends Properties {
	// ******************************** Variables de clase

    /** A table of hex digits */
    private static final char[] hexDigit = {
	'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F'
    };

    private static final String specialSaveChars = "=: \t\r\n\f#!";
    private static final long serialVersionUID = 7001219701928891550L;


    // ******************************** Variables de instancia

	// ******************************** Constructores
	public SortedProperties() {
	}
	
	public SortedProperties(final Properties defaults) {
		super(defaults);
	}

	// ******************************** Metodos de instancia
    /**
	 * Tomado de Properties y modificado para que el almacenamiento lo haga en orden alfabético <BR> <BR>
     * Writes this property list (key and element pairs) in this
     * <code>Properties</code> table to the output stream in a format suitable
     * for loading into a <code>Properties</code> table using the
     * <code>load</code> method.
     * The stream is written using the ISO 8859-1 character encoding.
     * <p>
     * Properties from the defaults table of this <code>Properties</code>
     * table (if any) are <i>not</i> written out by this method.
     * <p>
     * If the header argument is not null, then an ASCII <code>#</code>
     * character, the header string, and a line separator are first written
     * to the output stream. Thus, the <code>header</code> can serve as an
     * identifying comment.
     * <p>
     * Next, a comment line is always written, consisting of an ASCII
     * <code>#</code> character, the current date and time (as if produced
     * by the <code>toString</code> method of <code>Date</code> for the
     * current time), and a line separator as generated by the Writer.
     * <p>
     * Then every entry in this <code>Properties</code> table is written out,
     * one per line. For each entry the key string is written, then an ASCII
     * <code>=</code>, then the associated element string. Each character of
     * the element string is examined to see whether it should be rendered as
     * an escape sequence. The ASCII characters <code>\</code>, tab, newline,
     * and carriage return are written as <code>\\</code>, <code>\t</code>,
     * <code>\n</code>, and <code>\r</code>, respectively. Characters less
     * than <code>&#92;u0020</code> and characters greater than
     * <code>&#92;u007E</code> are written as <code>&#92;u</code><i>xxxx</i> for
     * the appropriate hexadecimal value <i>xxxx</i>. Leading space characters,
     * but not embedded or trailing space characters, are written with a
     * preceding <code>\</code>. The key and value characters <code>#</code>,
     * <code>!</code>, <code>=</code>, and <code>:</code> are written with a
     * preceding slash to ensure that they are properly loaded.
     * <p>
     * After the entries have been written, the output stream is flushed.  The
     * output stream remains open after this method returns.
     *
     * @param   out      an output stream.
     * @param   header   a description of the property list.
     * @exception  IOException if writing this property list to the specified
     *             output stream throws an <tt>IOException</tt>.
     * @exception  ClassCastException  if this <code>Properties</code> object
     *             contains any keys or values that are not <code>Strings</code>.
     */
    @Override
	public synchronized void store(final OutputStream out, final String header)
    throws IOException
    {
        final BufferedWriter awriter;
        awriter = new BufferedWriter(new OutputStreamWriter(out, "8859_1"));
        if (header != null) {
			writeln(awriter, "#" + header);
		}
        writeln(awriter, "#" + new Date().toString());
		
//        for (Enumeration e = keys(); e.hasMoreElements();) {
//            String key = (String)e.nextElement();
//            String val = (String)get(key);
//            key = saveConvert(key, true);
//
//	    /* No need to escape embedded and trailing spaces for value, hence
//	     * pass false to flag.
//	     */
//            val = saveConvert(val, false);
//            writeln(awriter, key + "=" + val);
//        }

		final String[] keys = keySet().toArray(EMPTY_STRING_ARRAY);
		for(int i = 0; i < keys.length; i++) {
			keys[i] = saveConvert(keys[i], true);
		}
		Arrays.sort(keys, String::compareToIgnoreCase);
        for (final String key : keys) {
            String val = (String) get(key);
            val = saveConvert(val, false);
            writeln(awriter, new StringBuilder().append(key).append('=')
                .append(val).toString());
        }

        awriter.flush();
    }

    private static void writeln(final BufferedWriter bw, final String s) throws IOException {
        bw.write(s);
        bw.newLine();
    }

    /*
	 * Tomado de Properties <BR> <BR>
     * Converts unicodes to encoded &#92;uxxxx
     * and writes out any of the characters in specialSaveChars
     * with a preceding slash
     */
    private String saveConvert(final String theString, final boolean escapeSpace) {
        final int len = theString.length();
        final StringBuilder outBuffer = new StringBuilder(len * 2);

        for(int x=0; x<len; x++) {
            final char aChar = theString.charAt(x);
            switch(aChar) {
		case ' ':
		    if (x == 0 || escapeSpace) {
				outBuffer.append('\\');
			}

		    outBuffer.append(' ');
		    break;
                case '\\':outBuffer.append('\\'); outBuffer.append('\\');
                          break;
                case '\t':outBuffer.append('\\'); outBuffer.append('t');
                          break;
                case '\n':outBuffer.append('\\'); outBuffer.append('n');
                          break;
                case '\r':outBuffer.append('\\'); outBuffer.append('r');
                          break;
                case '\f':outBuffer.append('\\'); outBuffer.append('f');
                          break;
                default:
                    if ((aChar < 0x0020) || (aChar > 0x007e)) {
                        outBuffer.append('\\');
                        outBuffer.append('u');
                        outBuffer.append(toHex((aChar >> 12) & 0xF));
                        outBuffer.append(toHex((aChar >>  8) & 0xF));
                        outBuffer.append(toHex((aChar >>  4) & 0xF));
                        outBuffer.append(toHex( aChar        & 0xF));
                    } else {
                        if (specialSaveChars.indexOf(aChar) != -1) {
							outBuffer.append('\\');
						}
                        outBuffer.append(aChar);
                    }
            }
        }
        return outBuffer.toString();
    }

    /**
	 * Tomado de Properties <BR> <BR>
     * Convert a nibble to a hex character
     * @param	nibble	the nibble to convert.
     * @return the nibble converted to a hex character.
     */
    private static char toHex(final int nibble) {
	    return hexDigit[(nibble & 0xF)];
    }

	// ******************************** Metodos estaticos
}
