#
# Source configuration
#
dataSource=org.pclg.migrator.clarion.DataSourceClarion
sourceDatabase=C:\tmp
sourceTable=FECHAS.DAT
#
# Target configuration
#
dataSink=net.asintec.migrator.DataSinkJDBC
targetDriverName=org.gjt.mm.mysql.Driver
targetDbURL=jdbc:mysql://localhost/agenda
targetDatabase=C:\home\databases\FileDataBase.mdb
targetTable=contactos
#
# Fields correspondence
#
CLAVE|<AUTO>|1|||
VERSION|<CONSTANTE>|1|||
DELETED|<VACIO>||||
NOMBRE|NOMBRE||net.asintec.migrator.preprocessors.PreprocessorClipString||
APELLIDO|APELLIDO||net.asintec.migrator.preprocessors.PreprocessorClipString||
DIRECCION|<VACIO>||||
IMAGEN|<VACIO>||||
SEXO|SEXO||net.asintec.migrator.preprocessors.PreprocessorClipString||
PAIS|PAIS||net.asintec.migrator.preprocessors.PreprocessorClipString||
TELEFONO1|TELEFONO_1||net.asintec.migrator.preprocessors.PreprocessorClipString||
TELEFONO2|TELEFONO_2||net.asintec.migrator.preprocessors.PreprocessorClipString||
TELEFONO3|TELEFONO_3||net.asintec.migrator.preprocessors.PreprocessorClipString||
EMAIL|EMAIL||net.asintec.migrator.preprocessors.PreprocessorClipString||
DIA|DIA||||
MES|MES||||
ANO|ANO||org.pclg.migrator.preprocessors.PreprocessorAddCentury||
MARCA|MARCA||net.asintec.migrator.preprocessors.PreprocessorClipString||
FechaActualizacion|F_ACTUALIZ||org.pclg.migrator.clarion.PreprocessorClarionDate||
FechaCreacion|F_CREACION||org.pclg.migrator.clarion.PreprocessorClarionDate||
LISTAR|LISTAR||org.pclg.migrator.preprocessors.PreprocessorYesNo2OneZero||
NOTAS|NOTAS||net.asintec.migrator.preprocessors.PreprocessorClipString||
