#
# Source configuration
#
dataSource=org.pclg.migrator.clarion.DataSourceClarion
sourceDatabase=C:\tmp
sourceTable=FECHAS.DAT
#
# Target configuration
#
dataSink=net.asintec.migrator.DataSinkJDBC
targetDriverName=org.gjt.mm.mysql.Driver
targetDbURL=jdbc:mysql://localhost/agenda
targetDatabase=C:\home\databases\FileDataBase.mdb
targetTable=contactos
#
# Fields correspondence
#
CLAVE|<AUTO>|1|||
VERSION|<CONSTANTE>|1|||
DELETED|<VACIO>||||
NOMBRE|NOMBRE||org.pclg.agenda.crypto.PreprocessorClipAndCryptString||
APELLIDO|APELLIDO||org.pclg.agenda.crypto.PreprocessorClipAndCryptString||
DIRECCION|<VACIO>||||
IMAGEN|<VACIO>||||
SEXO|SEXO||org.pclg.agenda.crypto.PreprocessorClipAndCryptString||
PAIS|PAIS||org.pclg.agenda.crypto.PreprocessorClipAndCryptString||
TELEFONO1|TELEFONO_1||org.pclg.agenda.crypto.PreprocessorClipAndCryptString||
TELEFONO2|TELEFONO_2||org.pclg.agenda.crypto.PreprocessorClipAndCryptString||
TELEFONO3|TELEFONO_3||org.pclg.agenda.crypto.PreprocessorClipAndCryptString||
EMAIL|EMAIL||org.pclg.agenda.crypto.PreprocessorClipAndCryptString||
DIA|DIA||||
MES|MES||||
ANO|ANO||org.pclg.migrator.preprocessors.PreprocessorAddCentury||
MARCA|MARCA||org.pclg.agenda.crypto.PreprocessorClipAndCryptString||
FechaActualizacion|F_ACTUALIZ||org.pclg.migrator.clarion.PreprocessorClarionDate||
FechaCreacion|F_CREACION||org.pclg.migrator.clarion.PreprocessorClarionDate||
LISTAR|LISTAR||org.pclg.migrator.preprocessors.PreprocessorYesNo2OneZero||
NOTAS|NOTAS||org.pclg.agenda.crypto.PreprocessorClipAndCryptString||
