#
# Source configuration
#
dataSource=net.asintec.migrator.DataSourceJDBC
sourceDriverName=org.gjt.mm.mysql.Driver
sourceDbURL=jdbc:mysql://localhost/agenda
sourceTable=telefonos
#
# Target configuration
#
dataSink=net.asintec.migrator.DataSourceJDBC
targetDriverName=org.apache.derby.jdbc.EmbeddedDriver
targetDbURL=jdbc:derby:C:/tmp/agenda/agendaDB;create=true
targetTable=telefonos
#
# Fields correspondence
#
Clave|Clave||||
Version|Version||||
Secuencia|Secuencia||||
Numero|Numero||||
