#
# Source configuration
#
dataSource=net.asintec.migrator.DataSourceJDBC
sourceDriverName=org.gjt.mm.mysql.Driver
sourceDbURL=jdbc:mysql://localhost/agenda
sourceTable=contactos_cr
#
# Target configuration
#
dataSink=net.asintec.migrator.DataSourceJDBC
targetDriverName=org.gjt.mm.mysql.Driver
targetDbURL=jdbc:mysql://localhost/agenda
targetTable=contactos
#
# Fields correspondence
#
Clave|Clave||||
Version|Version||||
Deleted|Deleted||||
Nombre|Nombre||org.pclg.agenda.crypto.PreprocessorCryptString||
Apellido|Apellido||org.pclg.agenda.crypto.PreprocessorCryptString||
Imagen|Imagen||org.pclg.agenda.crypto.PreprocessorCryptString||
Sexo|Sexo||org.pclg.agenda.crypto.PreprocessorCryptString||
VersionTelefono|VersionTelefono||||
Pais|Pais||org.pclg.agenda.crypto.PreprocessorCryptString||
Email|Email||org.pclg.agenda.crypto.PreprocessorCryptString||
Dia|Dia||||
Mes|Mes||||
Ano|Ano||||
Marca|Marca||org.pclg.agenda.crypto.PreprocessorCryptString||
FechaActualizacion|FechaActualizacion||||
FechaCreacion|FechaCreacion||||
Listar|Listar||||
Notas|Notas||org.pclg.agenda.crypto.PreprocessorCryptString||
