package org.pclg.dbutil;

import org.apache.log4j.Logger;
import org.jpatterns.gof.CommandPattern;
import org.jpatterns.plopd.NullObjectPattern;
import org.pclg.log.LoggerFactory;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

public class VersatileConnection implements Connection {
	/** El logger. */
	private static final Logger LOGGER = LoggerFactory.makeLog4J();
	private static final String PREPARING_SQL = "Preparing SQL: ";
	private final Connection delegate;
	private final VersatileProcessor preprocessor;
	private final VersatileProcessor postprocessor;

	@CommandPattern.ConcreteCommand
	@NullObjectPattern.NullObject
	private static class NullProcessor implements VersatileProcessor {
		@Override
		public void go() {
			// Do nothing
		}
	}

	private static final NullProcessor nullProcessor = new NullProcessor();

	public VersatileConnection(final Connection delegate) {
		this(delegate, null, null);
	}

	public VersatileConnection(final Connection delegate, final VersatileProcessor preprocessor, final VersatileProcessor postprocessor) {
		this.delegate = delegate;
		this.preprocessor = preprocessor == null ? nullProcessor : preprocessor;
		this.postprocessor = postprocessor == null ? nullProcessor : postprocessor;
	}

	@Override
	public PreparedStatement prepareStatement(final String sql, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability) throws SQLException {
		LOGGER.info(PREPARING_SQL + sql);
		final PreparedStatement prepareStatement = delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
		return new VersatilePreparedStatement(prepareStatement, sql, preprocessor, postprocessor);
	}
	@Override
	public PreparedStatement prepareStatement(final String sql, final int resultSetType, final int resultSetConcurrency) throws SQLException {
		LOGGER.info(PREPARING_SQL + sql);
		final PreparedStatement prepareStatement = delegate.prepareStatement(sql, resultSetType, resultSetConcurrency);
		return new VersatilePreparedStatement(prepareStatement, sql, preprocessor, postprocessor);
	}
	@Override
	public PreparedStatement prepareStatement(final String sql, final int autoGeneratedKeys) throws SQLException {
		LOGGER.info(PREPARING_SQL + sql);
		final PreparedStatement prepareStatement = delegate.prepareStatement(sql, autoGeneratedKeys);
		return new VersatilePreparedStatement(prepareStatement, sql, preprocessor, postprocessor);
	}
	@Override
	public PreparedStatement prepareStatement(final String sql, final int[] columnIndexes) throws SQLException {
		LOGGER.info(PREPARING_SQL + sql);
		final PreparedStatement prepareStatement = delegate.prepareStatement(sql, columnIndexes);
		return new VersatilePreparedStatement(prepareStatement, sql, preprocessor, postprocessor);
	}
	@Override
	public PreparedStatement prepareStatement(final String sql, final String[] columnNames) throws SQLException {
		LOGGER.info(PREPARING_SQL + sql);
		final PreparedStatement prepareStatement = delegate.prepareStatement(sql, columnNames);
		return new VersatilePreparedStatement(prepareStatement, sql, preprocessor, postprocessor);
	}
	@Override
	public PreparedStatement prepareStatement(final String sql) throws SQLException {
		LOGGER.info(PREPARING_SQL + sql);
		final PreparedStatement prepareStatement = delegate.prepareStatement(sql);
		return new VersatilePreparedStatement(prepareStatement, sql, preprocessor, postprocessor);
	}

	@Override
	public Statement createStatement() throws SQLException {
		final Statement statement = delegate.createStatement();
		return new VersatileStatement(statement, preprocessor, postprocessor);
	}

	@Override
	public Statement createStatement(final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability) throws SQLException {
		final Statement statement = delegate.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability);
		return new VersatileStatement(statement, preprocessor, postprocessor);
	}

	@Override
	public Statement createStatement(final int resultSetType, final int resultSetConcurrency) throws SQLException {
		final Statement statement = delegate.createStatement(resultSetType, resultSetConcurrency);
		return new VersatileStatement(statement, preprocessor, postprocessor);
	}

	@Override
	public void clearWarnings() throws SQLException {
		delegate.clearWarnings();
	}

	@Override
	public void close() throws SQLException {
		delegate.close();
        LOGGER.info("Connection closed");
	}

	@Override
	public void commit() throws SQLException {
		delegate.commit();
		LOGGER.info("Transaction committed");
	}
	@Override
	public boolean getAutoCommit() throws SQLException {
		return delegate.getAutoCommit();
	}
	@Override
	public String getCatalog() throws SQLException {
		return delegate.getCatalog();
	}
	@Override
	public int getHoldability() throws SQLException {
		return delegate.getHoldability();
	}
	@Override
	public DatabaseMetaData getMetaData() throws SQLException {
		return delegate.getMetaData();
	}
	@Override
	public int getTransactionIsolation() throws SQLException {
		return delegate.getTransactionIsolation();
	}
	@Override
	public Map<String, Class<?>> getTypeMap() throws SQLException {
		return delegate.getTypeMap();
	}
	@Override
	public SQLWarning getWarnings() throws SQLException {
		return delegate.getWarnings();
	}
	@Override
	public boolean isClosed() throws SQLException {
		return delegate.isClosed();
	}
	@Override
	public boolean isReadOnly() throws SQLException {
		return delegate.isReadOnly();
	}
	@Override
	public String nativeSQL(final String sql) throws SQLException {
		return delegate.nativeSQL(sql);
	}
	@Override
	public CallableStatement prepareCall(final String sql, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability) throws SQLException {
		return delegate.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
	}
	@Override
	public CallableStatement prepareCall(final String sql, final int resultSetType, final int resultSetConcurrency) throws SQLException {
		return delegate.prepareCall(sql, resultSetType, resultSetConcurrency);
	}
	@Override
	public CallableStatement prepareCall(final String sql) throws SQLException {
		return delegate.prepareCall(sql);
	}
	@Override
	public void releaseSavepoint(final Savepoint savepoint) throws SQLException {
		delegate.releaseSavepoint(savepoint);
	}
	@Override
	public void rollback() throws SQLException {
		delegate.rollback();
		LOGGER.info("Transaction rolled back");
	}
	@Override
	public void rollback(final Savepoint savepoint) throws SQLException {
		delegate.rollback(savepoint);
		LOGGER.info("Transaction rolled back. Savepoint.id = " + savepoint.getSavepointId()
			+ ", Savepoint.name = " + savepoint.getSavepointName());
	}

	@Override
	public void setAutoCommit(final boolean autoCommit) throws SQLException {
		delegate.setAutoCommit(autoCommit);
	}
	@Override
	public void setCatalog(final String catalog) throws SQLException {
		delegate.setCatalog(catalog);
	}
	@Override
	public void setHoldability(final int holdability) throws SQLException {
		delegate.setHoldability(holdability);
	}
	@Override
	public void setReadOnly(final boolean readOnly) throws SQLException {
		delegate.setReadOnly(readOnly);
	}
	@Override
	public Savepoint setSavepoint() throws SQLException {
		return delegate.setSavepoint();
	}
	@Override
	public Savepoint setSavepoint(final String name) throws SQLException {
		return delegate.setSavepoint(name);
	}
	@Override
	public void setTransactionIsolation(final int level) throws SQLException {
		delegate.setTransactionIsolation(level);
	}
	@Override
	public void setTypeMap(final Map<String, Class<?>> arg0) throws SQLException {
		delegate.setTypeMap(arg0);
	}
	@Override
	public Array createArrayOf(final String typeName, final Object[] elements) throws SQLException {
		return delegate.createArrayOf(typeName, elements);
	}
	@Override
	public Blob createBlob() throws SQLException {
		return delegate.createBlob();
	}
	@Override
	public Clob createClob() throws SQLException {
		return delegate.createClob();
	}
	@Override
	public NClob createNClob() throws SQLException {
		return delegate.createNClob();
	}
	@Override
	public SQLXML createSQLXML() throws SQLException {
		return delegate.createSQLXML();
	}
	@Override
	public Struct createStruct(final String typeName, final Object[] attributes) throws SQLException {
		return delegate.createStruct(typeName, attributes);
	}
	@Override
	public Properties getClientInfo() throws SQLException {
		return delegate.getClientInfo();
	}
	@Override
	public String getClientInfo(final String name) throws SQLException {
		return delegate.getClientInfo(name);
	}
	@Override
	public boolean isValid(final int timeout) throws SQLException {
		return delegate.isValid(timeout);
	}
	@Override
	public boolean isWrapperFor(final Class<?> iface) throws SQLException {
		return delegate.isWrapperFor(iface);
	}
	@Override
	public void setClientInfo(final Properties properties) throws SQLClientInfoException {
		delegate.setClientInfo(properties);
	}
	@Override
	public void setClientInfo(final String name, final String value) throws SQLClientInfoException {
		delegate.setClientInfo(name, value);
	}
	@Override
	public <T> T unwrap(final Class<T> iface) throws SQLException {
		return delegate.unwrap(iface);
	}

	@Override
	public void abort(final Executor executor) throws SQLException {
		delegate.abort(executor);
	}

	@Override
	public int getNetworkTimeout() throws SQLException {
		return delegate.getNetworkTimeout();
	}

	@Override
	public String getSchema() throws SQLException {
		return delegate.getSchema();
	}

	@Override
	public void setNetworkTimeout(final Executor executor,
			final int milliseconds) throws SQLException {
		delegate.setNetworkTimeout(executor, milliseconds);
	}

	@Override
	public void setSchema(final String schema) throws SQLException {
		delegate.setSchema(schema);
	}
}
