new.record.image=/resources/images/16x16/user-new-3.png
copy.record.image=/resources/images/16x16/edit-copy-7.png
paste.record.image=/resources/images/16x16/edit-paste-7.png
exit.system.image=/resources/images/16x16/system-exit.png
Agenda.image=/resources/images/24x24/address-book-new-2.png
Agenda.SplashWindow.image=/resources/images/Please_stand_by.png
AgendaGUI.customQueryImage=/resources/images/16x16/insert-query.png
AgendaGUI.byNameImage=/resources/images/16x16/format-text-bold-3.png
AgendaGUI.recentlyModifiedImage=/resources/images/16x16/document-open-recent-3.png
AgendaGUI.filteredImage=/resources/images/16x16/edit-find-7.png
AgendaGUI.byMarkImage=/resources/images/16x16/dialog-apply.png
AgendaGUI.byDateImage=/resources/images/16x16/view-pim-calendar.png
AgendaGUI.byInterestingDateImage=/resources/images/16x16/view-calendar-upcoming-events.png
AgendaGUI.byBirthdayImage=/resources/images/16x16/go-jump-today.png
AgendaGUI.byGroupImage=/resources/images/16x16/edit-group.png
AgendaGUI.byGroupImageBig=/resources/images/32x32/edit-group.png
AgendaGUI.countryImage=/resources/images/16x16/applications-internet-2.png
AgendaGUI.countryImageBig=/resources/images/32x32/applications-internet-2.png
AgendaGUI.deletedImage=/resources/images/16x16/edit-delete-shred.png
AgendaGUI.printImage=/resources/images/16x16/printer-4.png
AgendaGUI.fortunesImage=/resources/images/16x16/ksmiletris.png
AgendaGUI.settingsImage=/resources/images/16x16/preferences-desktop-2.png
AgendaGUI.systemInfoImage=/resources/images/16x16/development-java-3.png
AgendaGUI.viewLogImage=/resources/images/16x16/icons8-edit-property-16.png
AgendaGUI.menu.file.copy.database.image=/resources/images/16x16/database-save.png
AgendaGUI.menu.file.plugin.image=/resources/images/16x16/plugin-go.png
AgendaGUI.menu.file.change.database.image=/resources/images/16x16/plugin-go.png
CancelImage=/resources/images/16x16/dialog-cancel-7.png
PrintForm.previewImage=/resources/images/16x16/document-print-preview-2.png
PrintForm.newImage=/resources/images/16x16/layer-new.png
PrintForm.printImage=/resources/images/16x16/printer-4.png
btnPrevImage=/toolbarButtonGraphics/navigation/Back16.gif
btnNextImage=/toolbarButtonGraphics/navigation/Forward16.gif
DataEntry.AcceptImage=/resources/images/16x16/dialog-apply.png
ImageButton.image=/resources/images/128x128/image-x-pentax-pef.png
ImageButton.image.notFound=/resources/images/128x128/edit-bomb.png
AgendaGUI.VCardImage=/resources/images/16x16/vcard.png
AgendaGUI.SaveVCardImage=/resources/images/16x16/vcard-edit.png
AgendaGUI.ReadVCardImage=/resources/images/16x16/vcard-add.png
AgendaGUI.saveAllRecordsImage=/resources/images/16x16/document-save-all.png
AgendaGUI.closeAllRecordsImage=/resources/images/16x16/tab-close-other.png
AgendaGUI.customQueryDialogImage=/resources/images/32x32/db_status.png
AgendaGUI.phoneTypeImage=/resources/images/16x16/telephone.png
AgendaGUI.phoneTypeImageBig=/resources/images/32x32/phone-2.png
AgendaGUI.i18n.emblem=/resources/images/16x16/emblems/es.png
PluginAction.dialogImage=/resources/images/32x32/kommando.png
unknownWomanImage=/resources/images/unknown-woman.png
unknownManImage=/resources/images/unknown-man.png

PasswordDialog.warning.icon=/toolbarButtonGraphics/com_incors_plaf_alloy_icons/Warn.png
