#Configuracion de AgendaGUI
#Fri Aug 03 17:53:10 CEST 2018
Agenda.default.country=34
Agenda.FortunesAtStartup=true
Agenda.InterestingDatesAtStartup=true
AgendaDb.daysFork4Birthdays=10
AgendaDb.daysFork4InterestingDates=10
AgendaDb.daysFork4RecentlyModified=4
AgendaDb.interestingDatesDivisor=500
AgendaGUI.lastVCardsDirectory=C\:\\tmp
Application.ForceLanguage=de
applicationBounds.h=882
applicationBounds.w=1292
applicationBounds.x=0
applicationBounds.y=7
Col0Visible=false
Col1Visible=false
Col2Pos=0
Col2Visible=true
Col2Width=306
Col3Pos=1
Col3Visible=true
Col3Width=295
Col4Pos=2
Col4Visible=true
Col4Width=309
Col5Pos=3
Col5Visible=true
Col5Width=366
Col6Visible=false
Col7Visible=false
DataEntry.lastImagesDirectory=C\:\\home\\img\\fotos\\Latorraca 2013_11_05
PluginAction.item.0=org.pclg.agenda.plugins.CheckAgendaPhotos
PluginAction.item.1=org.pclg.agenda.plugins.PopulateThumbnails
PluginAction.item.2=org.pclg.agenda.plugins.MigrateDirecciones
PluginAction.item.3=org.pclg.agenda.plugins.NormalizeTelephones
PluginAction.item.4=org.pclg.agenda.plugins.SimpleQueryPlugin  update imagen set imagen \= 'C\:\\home\\img\\fotos\\Daniel naci\u00F3 el 9 de marzo de 2016.jpg'  where clave \= 447
PluginAction.item.5=org.pclg.agenda.plugins.SimpleQueryPlugin  select imagen from imagen  where clave \=447
PluginAction.item.6=org.pclg.agenda.plugins.SimpleQueryPlugin  select apellido from contactos  where clave \=432
PluginAction.item.7=org.pclg.agenda.plugins.SimpleQueryPlugin  select apellido from contactos  where clave > 22
PluginAction.item.8=org.pclg.agenda.plugins.SimpleQueryPlugin  delete from root.grupo where clave > 22
PluginAction.item.9=org.pclg.agenda.plugins.SimpleQuery  delete from root.grupo where clave > 22
PluginAction.maxHistory=10
QueryAction.item.0=versionimagen > 0 and marca is not null and marca <> ''
QueryAction.item.1=Sexo \= 'F' AND SUBSTR(Nombre, 1, 1) IN ('B', 'H', '\u00D1', 'Q', 'T', 'U', 'V', 'W', 'Z') AND NOT Deleted
QueryAction.item.10=versionimagen > 0 and marca is not null
QueryAction.item.11=mes between 2 and 3
QueryAction.item.2=versionimagen > 0
QueryAction.item.3=Sexo \= 'F' AND SUBSTR(Nombre, 1, 1) IN ('B', 'H', '\u00D1', 'O', 'Q', 'T', 'U', 'V', 'W', 'Z') AND NOT Deleted
QueryAction.item.4=mes \= 12
QueryAction.item.5=versionimagen \= 0 and marca is not null and marca <> ''
QueryAction.item.6=versionimagen > 0 and (marca is null or marca \= '')
QueryAction.item.7=versionimagen \= 0
QueryAction.item.8=mes \= 3
QueryAction.item.9=dia \= 25
QueryAction.maxHistory=20
