new.record.image=/images/16x16/user-new-3.png
copy.record.image=/images/16x16/edit-copy-7.png
paste.record.image=/images/16x16/edit-paste-7.png
exit.system.image=/images/16x16/system-exit.png
Agenda.image=/images/24x24/address-book-new-2.png
Agenda.SplashWindow.image=/images/Please_stand_by.png
AgendaGUI.customQueryImage=/images/16x16/insert-query.png
AgendaGUI.byNameImage=/images/16x16/format-text-bold-3.png
AgendaGUI.recentlyModifiedImage=/images/16x16/document-open-recent-3.png
AgendaGUI.filteredImage=/images/16x16/edit-find-7.png
AgendaGUI.byMarkImage=/images/16x16/dialog-apply.png
AgendaGUI.byDateImage=/images/16x16/view-pim-calendar.png
AgendaGUI.byInterestingDateImage=/images/16x16/view-calendar-upcoming-events.png
AgendaGUI.byBirthdayImage=/images/16x16/go-jump-today.png
AgendaGUI.byGroupImage=/images/16x16/edit-group.png
AgendaGUI.byGroupImageBig=/images/32x32/edit-group.png
AgendaGUI.countryImage=/images/16x16/applications-internet-2.png
AgendaGUI.countryImageBig=/images/32x32/applications-internet-2.png
AgendaGUI.deletedImage=/images/16x16/edit-delete-shred.png
AgendaGUI.printImage=/images/16x16/printer-4.png
AgendaGUI.fortunesImage=/images/16x16/ksmiletris.png
AgendaGUI.settingsImage=/images/16x16/preferences-desktop-2.png
AgendaGUI.systemInfoImage=/images/16x16/development-java-3.png
AgendaGUI.viewLogImage=/images/16x16/icons8-edit-property-16.png
AgendaGUI.menu.file.copy.database.image=/images/16x16/database-save.png
AgendaGUI.menu.file.plugin.image=/images/16x16/plugin-go.png
AgendaGUI.menu.file.change.database.image=/images/16x16/plugin-go.png
CancelImage=/images/16x16/dialog-cancel-7.png
PrintForm.previewImage=/images/16x16/document-print-preview-2.png
PrintForm.newImage=/images/16x16/layer-new.png
PrintForm.printImage=/images/16x16/printer-4.png
btnPrevImage=/toolbarButtonGraphics/navigation/Back16.gif
btnNextImage=/toolbarButtonGraphics/navigation/Forward16.gif
DataEntry.AcceptImage=/images/16x16/dialog-apply.png
ImageButton.image=/images/128x128/image-x-pentax-pef.png
ImageButton.image.notFound=/images/128x128/edit-bomb.png
AgendaGUI.VCardImage=/images/16x16/vcard.png
AgendaGUI.SaveVCardImage=/images/16x16/vcard-edit.png
AgendaGUI.ReadVCardImage=/images/16x16/vcard-add.png
AgendaGUI.saveAllRecordsImage=/images/16x16/document-save-all.png
AgendaGUI.closeAllRecordsImage=/images/16x16/tab-close-other.png
AgendaGUI.customQueryDialogImage=/images/32x32/db_status.png
AgendaGUI.phoneTypeImage=/images/16x16/telephone.png
AgendaGUI.phoneTypeImageBig=/images/32x32/phone-2.png
AgendaGUI.i18n.emblem=/images/16x16/emblems/es.png
PluginAction.dialogImage=/images/32x32/kommando.png
unknownWomanImage=/images/unknown-woman.png
unknownManImage=/images/unknown-man.png

PasswordDialog.warning.icon=/toolbarButtonGraphics/com_incors_plaf_alloy_icons/Warn.png
