Application.Title = Modificador del nombre de archivos
erroresLbl = Errores
idiomaLbl = Idioma
prefixLbl = prefix
startLbl = start
lengthLbl = length
rellenoLbl = relleno
exitLbl = &Salir par co\u00F1o
menu.file = \u00a9 El Zorro \u00ae \u2221 \u2122
TestBox.realThingLbl = Real thing
TestBox.testLbl = Test
consoleLbl = Consola
allFilesLbl = All files
erroresSound = /img/pkg5230_.wav
espanaLbl = &Espa\u00F1a
franceLbl = &France
englandLbl = &England
deutschlandLbl = &Deutschland
sampleLbl=Muestra (double-click en el archivo para seleccionar)\:
clear.tooltip.text = Limpiar los campos
undo.tooltip.text = Deshacer los \u00FAltimos cambios
redo.tooltip.text = Rehacer los \u00FAltimos cambios des-hechos
zero.tooltip.text = Pone un '0' antes de los digitos menores que 10
test.tooltip.text = Probar los cambios
exit.tooltip.text = Fin de la aplicaci\u00F3n chaval
clear.label = Clear
undo.label = Undo
redo.label = Redo
zero.label = '0' antes de los digitos
test.label = Test
exit.label = Exit
ButonPanel.lowerBt.text = Min\u00FAsculas
ButonPanel.orderBt.text = Ordenar
ButonPanel._Bt.text = Antes de la extensi\u00F3n
ButonPanel._Bt.tooltip = Coloca el caracter indicado antes del \u00FAltimo '.'
ButonPanel.__Bt.text = Cambiar ' ' por '_'
ButonPanel.replaceBt.text = Reemplazar
ButonPanel.ezrepBt.text = Nombre del dir
ButonPanel.ezrepBt.tooltip = Antepone el nombre del directorio
ButonPanel.compBt.text = Comparar
ButonPanel.compBt.tooltip = Ejecuta Comp.class
ButonPanel.viewBt.text = Ver (To Do)
ButonPanel.viewBt.tooltip = Un visor de archivos\: No est\u00E1 implementado
ButonPanel.quitBt.text = Salir par co\u00F1o
ButonPanel.quitBt.tooltip = Fin de la aplicaci\u00F3n
ButonPanel.orderChoice.asc = Asc.
ButonPanel.orderChoice.desc = Desc.
ButonPanel.orderChoice.alfa = Alfa
FileListPanel.filter.prompt=Escoja o introduzca el filtro a usar (regex)
FileListPanel.filter.dialogImage=/images/32x32/kommando.png
FileListPanel.filter.OK=Yes man!
FileListPanel.filter.KO=No way!
