##La lista, separada por '|' de los archivos o directorios a agregar al
#classpath the la aplicación.
Application.ClassPath=C:/home/development/lib/lib_L&F
Application.ForceLanguage=it

lafName=net.beeger.squareness.SquarenessLookAndFeel
lafThemeName=javax.swing.plaf.metal.DefaultMetalTheme
