#Jars, directories or files needed in the classpath
#delimited by | (spaces are not trimmed)
classpathEntries=C:/home/development/lib/log4j-1.2.15.jar
dbConnnectionInfoFile=CompDel_Derby.info
undoFileLocation=C:/tmp