applicationBounds.h=532
applicationBounds.w=1025
applicationBounds.x=0
applicationBounds.y=0
errConsoleBounds.h=173
errConsoleBounds.w=953
errConsoleBounds.x=26
errConsoleBounds.y=536
excludeList=C\:\\RECYCLER|D\:\\RECYCLER|E\:\\RECYCLER|C\:\\windows|C\:\\Program Files|C\:\\images|D\:\\images|E\:\\images|C\:\\home\\databases|C\:\\sistema|C\:\\musique|C\:\\jdk|C\:\\home\\peliculas|C\:\\Cdu|
lastFirstDir=D\:\\tmp
lastSecondDir=C\:\\tmp
scrollBarPosition=nothing
undoFileLocation=C\:\\tmp