##SQLs para la inicializacion de la aplicación
# suppress inspection "UnusedProperty" for whole file

DirectorySynchronizer.driver=org.apache.derby.jdbc.EmbeddedDriver
#DirectorySynchronizer.path=/tmp/_Databases/DirectorySynchronizer
DirectorySynchronizer.url=jdbc:derby:/tmp/_Databases/DirectorySynchronizer;create=true;collation=TERRITORY_BASED:PRIMARY
DirectorySynchronizer.shutdown.url=jdbc:derby:/tmp/_Databases/DirectorySynchronizer;shutdown=true

DirectorySynchronizer.tables=CONTROL;Files

DirectorySynchronizer.createFiles=CREATE TABLE Files (\
	path         VARCHAR(2048) NOT NULL PRIMARY KEY,\
    lastModified TIMESTAMP NOT NULL\
)

DirectorySynchronizer.createCONTROL=CREATE TABLE CONTROL(\
	FechaActualizacion TIMESTAMP\
)

DirectorySynchronizer.populateCONTROL=INSERT INTO CONTROL VALUES\
	(NULL)
