# Las claves que comienzan con 'EXT_' son los recursos para las distintas
# extensiones de los archivos
#EXT_dat=Datos@#@/resources/images/gopher-binary.gif
#EXT_gif=Imagen GIF@#@/resources/images/gifIcon.gif
#EXT_ico=Icono@#@/resources/images/edit.gif
#EXT_jar=Java archive@#@/resources/images/Jar16.gif
#EXT_jpg=Imagen JPEG@#@/resources/images/jpgIcon.jpg
#EXT_jude=Diagrama UML de Jude@#@/resources/images/jude-doc.jpg
#EXT_log=Registro de actividades@#@/resources/images/doc.gif
#EXT_png=Imagen JPEG@#@/resources/images/jpgIcon.jpg
#EXT_properties=Configuracion de aplicacion@#@/resources/images/doc.gif
#EXT_txt=Documento de texto@#@/resources/images/doc.gif
no_access_dir=D:/plucien/Reise/agenda/org
error_obteniendo_recursos = Error obteniendo recursos para clave {0}.