##La lista, separada por '|' de los archivos o directorios a agregar al
#classpath the la aplicación.
FortunesDb.ClassPath=C:/home/development/lib/derby.jar

#Configuación para Derby
FortunesDb.driver=org.apache.derby.jdbc.EmbeddedDriver
FortunesDb.url=jdbc:derby:/_Agenda/fortunesDB;create=false

#Directory containing the fortune files (used by the loader)
FortunesDb.sourceDir=C:/home/development/modules/src/fortunes