#Nombre del menu y nombre de la clase del Ltema
#
#Mon Aug 21 18:02:09 CEST 2017
org.pclg.gui.temas.EcoTheme=EcoTheme
org.pclg.gui.temas.ReallyRandomTheme=ReallyRandomTheme
org.pclg.gui.temas.RandomTheme=RandomTheme
com.incors.plaf.kunststoff.themes.KunststoffNotebookTheme=KunststoffNotebookTheme
com.incors.plaf.kunststoff.themes.KunststoffPresentationTheme=KunststoffPresentationTheme
org.pclg.gui.temas.MonoTheme=MonoTheme
javax.swing.plaf.metal.DefaultMetalTheme=DefaultMetalTheme
com.incors.plaf.kunststoff.themes.KunststoffDesktopTheme=KunststoffDesktopTheme
