MP3Update.configFileAction=Config file
MP3Update.sampleConfigFileAction=Show sample
MP3Update.consoleTitle=Output
MP3Update.deleteId3v2=Delete Id3V2 tag
MP3Update.goAction=GO
MP3Update.image=/resources/images/24x24/multimedia-audio.png
MP3Update.overwrite=Overwrite existing tags
MP3Update.prefixLen=Prefix length
MP3Update.prefixLenTT=Length of the prefix of the filename that will not be part of the name of the song (ex.: 3 for 'nn-')
MP3Update.preserveAttributes=Preserve file attributes
MP3Update.recurse=Recurse
MP3Update.replaceChars=Replace chars
MP3Update.replaceCharsTT=Format: <char(s) to replace>|<replacement char(s),,<char(s) to replace>|<replacement char(s),,...
MP3Update.suffixLen=Suffix length
MP3Update.suffixLenTT=Length of the suffix of the filename that will not be part of the name of the song (ex.: 4 for '.mp3')
MP3Update.year=Year
MP3Update.yearTT=Year of the album (active if not recurse)
MP3Update.targetDir=Target dir
MP3Update.testOnly=Test only
MP3Update.textFiles=Text files
MP3Update.title=MP3Updater
MP3Update.trackNrFromPrefix=Take track nr. from prefix (nn-)
MP3Update.useInternalName=Use internal name
