ProcessLauncher.FilePath = C:/home/Finance/GnuCashData/Ex-Qdata/ExQdata.gnucash
ProcessLauncher.CommandPath = C:/usr/local/gnucash/bin/gnucash.exe
ProcessLauncher.Password = Ep+vdr11

ProcessLauncher.showInfoPanel = true
ProcessLauncher.show.stdout = false
ProcessLauncher.show.stderr = false
