ProcessLauncher.FilePath = /home/pablo/Finance/GnuCashData/Ex-Qdata/ExQdata.gnucash
ProcessLauncher.CommandPath = /usr/bin/gnucash
ProcessLauncher.Password =

ProcessLauncher.showInfoPanel = true
ProcessLauncher.show.stdout = false
ProcessLauncher.show.stderr = false