VideoCatalog.password=123456789
VideoCatalog.user=root
VideoCatalog.driver=org.apache.derby.jdbc.EmbeddedDriver
VideoCatalog.url=jdbc:derby:C:/tmp/_Agenda/VideoCatalogDB;create=true;collation=TERRITORY_BASED:PRIMARY;dataEncryption=true;bootPassword=123456789