##SQLs para la inicializacion de la aplicación

# suppress inspection "UnusedProperty" for whole file

#La lista, separada por ';' de las tablas de la aplicación.
#Al crear las tablas se ejecutan todas las sentencias VideoCatalog.create<tabla> y
#VideoCatalog.populate<tabla>, VideoCatalog.createINDEX_<tabla>?
#y eventualmente DROP TABLE <tabla>
VideoCatalog.tables=CONTROL;Videos

VideoCatalog.createVideos=CREATE TABLE NOTA(\
    Clave INTEGER NOT NULL,\
    Name VARCHAR(200),\
    PRIMARY KEY (Clave)\
)

VideoCatalog.createCONTROL=CREATE TABLE CONTROL(\
	FechaActualizacion TIMESTAMP\
)

VideoCatalog.populateCONTROL=INSERT INTO CONTROL VALUES\
	(NULL)
