#Configuration of misc.sopra.OuvrirSuivi application
#   Message to be shown if the target file doesn't exist. Only argument: file name
file.not.exists.msg=Parece que {0} no existe\n¿Hablar con pilotaje?\n¿Tener paciencia?
msg.box.title=Datei nicht gefunden
#Actions to take in this case.
action.wait=Esperar
action.previuosWeek=Ouvrir semaine précédente
action.copyGenericFile=Copy the generic file
action.copyEtPrevious=Copy the generic and open previous

#Intervalo de generación (WEEK or MONTH)
spanInterval=WEEK

# File name pattern. First argument  = date du jour 
#NIMS
#file.pattern=G:/CSMD_3-NIMS2/PRJ-P-1-CRISTALIN/PRJ-P4-Release/P40-Cristalin_GLOBAL/14-suivi_Hebdo_{0,date,yyyy}_{0,date,w}_NIMS.xls
#ULIS
#file.pattern=G:/CSMD_3-ULIS/INT-I2-GestionProjet/I21-Pilotage/I211-V1/SuiviTâches/Suivi BO/Tableau de bord BO - ULIS NG S{0,date,w}.xls
#BNP
#file.pattern=S:/80-SousTraitant/40-SOPRA_DISTRI/DMAQ/INT-I2-GestionProjet/I23-QualitéInt/I232 - CRA Detailles/{0,date,yyyy}/{0,date,MM}-{0,date,MMMM}/RA_PLU_{0,date,yyyy}{0,date,MM}_v2.5.xlsm
#BNP depuis 08/2013
#file.pattern=S:/80-SousTraitant/40-SOPRA_DISTRI/DMAQ/INT-I2-GestionProjet/I23-QualitéInt/I232 - CRA Detailles/{0,date,yyyy}/{0,date,yyyy}{0,date,MM}/RA_PLU_{0,date,yyyy}{0,date,MM}_v2.5.xlsm
#BNP depuis 09/2013
#file.pattern=O:/Technologie/PRIVE_SOPRA/DGO/DMAQ/INT-I2-GestionProjet/I23-QualitéInt/I232 - CRA Detailles/{0,date,yyyy}/{0,date,yyyy}{0,date,MM}/RA_PLU_{0,date,yyyy}{0,date,MM}_v2.5.xlsm
#BNP depuis 11/2013
#file.pattern=O:/Technologie/PRIVE_SOPRA/DGO/DMAQ/INT-I2-GestionProjet/I23-QualitéInt/I232 - CRA Detailles/{0,date,yyyy}/{0,date,yyyy}{0,date,MM}/RA_PLU_{0,date,yyyy}{0,date,MM} v3.1.xls
#BNP depuis 01/2014
#file.pattern=O:/Technologie/PRIVE_SOPRA/DGO/DMAQ/INT-I2-GestionProjet/I23-QualitéInt/I232 - CRA Detailles/{0,date,yyyy}/{0,date,yyyy}{0,date,MM}/RA_YYY_{0,date,yyyy}{0,date,MM} v3.2.xls

#Trigramme associated to the file to be opened
targetTrigramme=PLU
#Trigramme associated to the generic CRA file to be copied if it exists
genericTrigramme=XXX

#File name pattern since 09/01/2014. {0} argument  = date du jour, {1} argument  = trigramme
#file.pattern=O:/Technologie/PRIVE_SOPRA/DGO/DMAQ/INT-I2-GestionProjet/I23-QualitéInt/I232 - CRA Detailles/{0,date,yyyy}/{0,date,yyyy}{0,date,MM}/RA_{1}_{0,date,yyyy}{0,date,MM} v3.2.xls
#BNP depuis 04/2014
#file.pattern=O:/Technologie/PRIVE_SOPRA/DGO/DMAQ/INT-I2-GestionProjet/I23-QualitéInt/I232 - CRA Detailles/{0,date,yyyy}/{0,date,yyyy}{0,date,MM}/RA_{1}_{0,date,yyyy}{0,date,MM}_v3.4.xls
#BNP depuis 05/2014
#file.pattern=O:/Technologie/PRIVE_SOPRA/DGO/DMAQ/INT-I2-GestionProjet/I23-QualitéInt/I232 - CRA Detailles/{0,date,yyyy}/{0,date,yyyy}{0,date,MM}/RA_{1}_{0,date,yyyy}{0,date,MM}_v3.5.xls
#BNP depuis mi-06/2014 - Coño, a ver si se deciden de una puta vez!!!!
#file.pattern=O:/Technologie/PRIVE_SOPRA/TMA/INT-I2-GestionProjet/I23-QualitéInt/I234-CRA Detaillés/{0,date,yyyy}{0,date,MM}/RA_{1}_{0,date,yyyy}{0,date,MM}_v3.16.xls
#Bueno, ya me cansé. Vamos a intentarlo con una regex para la versión.
#file.pattern=O:/Technologie/PRIVE_SOPRA/TMA/INT-I2-GestionProjet/I23-QualitéInt/I234-CRA Detaillés/{0,date,yyyy}{0,date,MM}/RA_{1}_{0,date,yyyy}{0,date,MM}_v\\d+\.\\d+\.xls
#Coño, cómo joden!! 03/2015
file.pattern=O:/Technologie/PRIVE_SOPRA/TMA/INT-I2-GestionProjet/I23-QualitéInt/I234-CRA Detaillés/{0,date,yyyy}{0,date,MM}/RA_{1}_{0,date,yyyy}{0,date,MM}_v\\d+\.\\d+\.xlsm
