package org.pclg.dbutil;

import org.apache.log4j.Logger;
import org.pclg.log.LoggerFactory;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;


class VersatileStatement implements Statement {
	/** El logger. */
	private static final Logger LOGGER = LoggerFactory.makeLog4J();
	private final Statement delegate;
	private static final String MESSAGE = "Executing: %s";
	private final VersatileProcessor preprocessor;
	private final VersatileProcessor postprocessor;

	VersatileStatement(final Statement delegate, final VersatileProcessor preprocessor, final VersatileProcessor postprocessor) {
		this.delegate = delegate;
        this.preprocessor = preprocessor;
        this.postprocessor = postprocessor;
	}

	@Override
	public ResultSet executeQuery(final String sql) throws SQLException {
        LOGGER.debug(String.format(MESSAGE, sql));
        // WARNING: Do not use the pre and postprocessor here!
		return new VersatileResultSet(delegate.executeQuery(sql));
	}

	@Override
	public ResultSet getResultSet() throws SQLException {
		return new VersatileResultSet(delegate.getResultSet());
	}

	@Override
	public void addBatch(final String sql) throws SQLException {
		delegate.addBatch(sql);
	}

	@Override
	public void cancel() throws SQLException {
		delegate.cancel();
	}

	@Override
	public void clearBatch() throws SQLException {
		delegate.clearBatch();
	}

	@Override
	public void clearWarnings() throws SQLException {
		delegate.clearWarnings();
	}

	@Override
	public void close() throws SQLException {
		delegate.close();
	}

	@Override
	public boolean execute(final String sql, final int autoGeneratedKeys) throws SQLException {
		LOGGER.debug(String.format(MESSAGE, sql));
		preprocessor.go();
        final boolean result = delegate.execute(sql, autoGeneratedKeys);
        postprocessor.go();
        return result;
	}

	@Override
	public boolean execute(final String sql, final int[] columnIndexes) throws SQLException {
		LOGGER.debug(String.format(MESSAGE, sql));
		preprocessor.go();
        final boolean result = delegate.execute(sql, columnIndexes);
        postprocessor.go();
        return result;
	}

	@Override
	public boolean execute(final String sql, final String[] columnNames) throws SQLException {
		LOGGER.debug(String.format(MESSAGE, sql));
		preprocessor.go();
        final boolean result = delegate.execute(sql, columnNames);
        postprocessor.go();
        return result;
	}

	@Override
	public boolean execute(final String sql) throws SQLException {
		LOGGER.debug(String.format(MESSAGE, sql));
		preprocessor.go();
        final boolean result = delegate.execute(sql);
        postprocessor.go();
        return result;
	}

	@Override
	public int[] executeBatch() throws SQLException {
		LOGGER.debug(String.format(MESSAGE, "executeBatch()"));
		preprocessor.go();
        final int[] result = delegate.executeBatch();
        postprocessor.go();
        return result;
	}

	@Override
	public int executeUpdate(final String sql, final int autoGeneratedKeys) throws SQLException {
		LOGGER.debug(String.format(MESSAGE, sql));
		preprocessor.go();
        final int result = delegate.executeUpdate(sql, autoGeneratedKeys);
        postprocessor.go();
        return result;
	}

	@Override
	public int executeUpdate(final String sql, final int[] columnIndexes) throws SQLException {
		LOGGER.debug(String.format(MESSAGE, sql));
		preprocessor.go();
        final int result = delegate.executeUpdate(sql, columnIndexes);
        postprocessor.go();
        return result;
	}

	@Override
	public int executeUpdate(final String sql, final String[] columnNames) throws SQLException {
		LOGGER.debug(String.format(MESSAGE, sql));
		preprocessor.go();
        final int result = delegate.executeUpdate(sql, columnNames);
        postprocessor.go();
        return result;
	}

	@Override
	public int executeUpdate(final String sql) throws SQLException {
		LOGGER.debug(String.format(MESSAGE, sql));
		preprocessor.go();
        final int result = delegate.executeUpdate(sql);
        postprocessor.go();
        return result;
	}

	@Override
	public Connection getConnection() throws SQLException {
		return delegate.getConnection();
	}

	@Override
	public int getFetchDirection() throws SQLException {
		return delegate.getFetchDirection();
	}

	@Override
	public int getFetchSize() throws SQLException {
		return delegate.getFetchSize();
	}

	@Override
	public ResultSet getGeneratedKeys() throws SQLException {
		return new VersatileResultSet(delegate.getGeneratedKeys());
	}

	@Override
	public int getMaxFieldSize() throws SQLException {
		return delegate.getMaxFieldSize();
	}

	@Override
	public int getMaxRows() throws SQLException {
		return delegate.getMaxRows();
	}

	@Override
	public boolean getMoreResults() throws SQLException {
		return delegate.getMoreResults();
	}

	@Override
	public boolean getMoreResults(final int current) throws SQLException {
		return delegate.getMoreResults(current);
	}

	@Override
	public int getQueryTimeout() throws SQLException {
		return delegate.getQueryTimeout();
	}

	@Override
	public int getResultSetConcurrency() throws SQLException {
		return delegate.getResultSetConcurrency();
	}

	@Override
	public int getResultSetHoldability() throws SQLException {
		return delegate.getResultSetHoldability();
	}

	@Override
	public int getResultSetType() throws SQLException {
		return delegate.getResultSetType();
	}

	@Override
	public int getUpdateCount() throws SQLException {
		return delegate.getUpdateCount();
	}

	@Override
	public SQLWarning getWarnings() throws SQLException {
		return delegate.getWarnings();
	}

	@Override
	public void setCursorName(final String name) throws SQLException {
		delegate.setCursorName(name);
	}

	@Override
	public void setEscapeProcessing(final boolean enable) throws SQLException {
		delegate.setEscapeProcessing(enable);
	}

	@Override
	public void setFetchDirection(final int direction) throws SQLException {
		delegate.setFetchDirection(direction);
	}

	@Override
	public void setFetchSize(final int rows) throws SQLException {
		delegate.setFetchSize(rows);
	}

	@Override
	public void setMaxFieldSize(final int max) throws SQLException {
		delegate.setMaxFieldSize(max);
	}

	@Override
	public void setMaxRows(final int max) throws SQLException {
		delegate.setMaxRows(max);
	}

	@Override
	public void setQueryTimeout(final int seconds) throws SQLException {
		delegate.setQueryTimeout(seconds);
	}

	@Override
	public boolean isClosed() throws SQLException {
		return delegate.isClosed();
	}

	@Override
	public boolean isPoolable() throws SQLException {
		return delegate.isPoolable();
	}

	@Override
	public void closeOnCompletion() throws SQLException {
		delegate.closeOnCompletion();
	}

	@Override
	public boolean isCloseOnCompletion() throws SQLException {
		return delegate.isCloseOnCompletion();
	}

	@Override
	public boolean isWrapperFor(final Class<?> iface) throws SQLException {
		return delegate.isWrapperFor(iface);
	}

	@Override
	public void setPoolable(final boolean poolable) throws SQLException {
		delegate.setPoolable(poolable);
	}

	@Override
	public <T> T unwrap(final Class<T> iface) throws SQLException {
		return delegate.unwrap(iface);
	}
}
