##La lista, separada por '|' de los archivos o directorios a agregar al
#classpath the la aplicación.
#        commons-io-1.3.2.jar
#        docx4j-3.3.1.jar
#        guava-30.1-jre.jar
#        serializer-2.7.2.jar
#        slf4j-api-1.7.7.jar
#        xalan-2.7.2.jar
#Application.ClassPath=C:/home/development/lib/condominio

#El template a usar. Debe estar en el classpath (en mi caso está en el jar)
Template.Name=/La_comunidad_recto_y_verso_template_v3.docx

Output.Path=C:/tmp/Recibos_{0,date,yyyy}-{0,date,MM}.docx

# Datos para la impresión
receiptsPerMonth = 6
lastReceiptNr = 1000
receiptDateBegin = 01/2023
receiptDateEnd = 12/2023

# Los números usan . como separador decimal y no usan separador de millares
startBankBalance=0
startCashBalance=0

endBankBalance=0
endCashBalance=0

communityIn=0
waterIn=0

communityOwed=0
waterOwed=0

# El monto debe estar separado del texto por al menos un espacio; las lineas por un pipe.
expenseLines=
#Comisiones (Bankia): 6.50|\
#Luz (Gas Natural Fenosa): 6.17|\
#Agua (Canal): 137.84|\
#Agua (Ista Metering): 24.66

#Portillo telecom: 181.70|