# Dw's configuration file
#
# En modo verbose va diciendo el nombre de los archivos que está descargando.
verbose=false
# En modo debug muestra los stacktrace. de resto sólo muestra la excepcion.
debug=true
retries=5
http.proxySet=true
#Tamaño del pool de threads
poolSize=10

#BNP
http.proxyHost=vip-proxy-ass.fr.net.intra
http.proxyPort=8080
http.proxyUser=924461
http.proxyPassword=Lccsep17!

#Sopra
#http.proxyHost=alca.proxy.corp.sopra
#http.proxyHost=172.31.73.27
#http.proxyPort=8080

#ECI
#http.proxyHost=proxycint01.eci.geci
#http.proxyUser=35315354
#http.proxyPassword=125518

#Las Rozas?
#http.proxyUser=U009999
#http.proxyPassword=ab0d2
