#
# Servlets Properties
#
# servlet.<name>.code=class name (foo or foo.class)
# servlet.<name>.initArgs=comma-delimited list of {name, value} pairs
#			  that can be accessed by the servlet using the
#			  servlet API calls
#

# trucks servlet
servlet.trucks.code=WDispatcher
servlet.trucks.initArgs=\
	auditStr=123,\
	withTrackerApplet=true,\
	userTimeout=10,\
	dataTimeout=10000,\
	debugLevel=1,\
	dataHost=161.196.58.51,\
	dataPort=5555,\
	servletHost=161.196.58.51,\
	servletPort=8080,\
	httpHost=161.196.58.51,\
	httpPort=80,\
	httpDir=pablo,\
	templatesDir=/export/home/pablo/tera/templates/,\
	welcomePage=Trucks.html
