<project name="pclg-tools" default="build" basedir="../../../..">

    <description>Builds pclg tools</description>

    <!-- Make sure Java 11 version is being used -->

<!--    <condition property="java11">-->
<!--        <javaversion atleast="11"/>-->
<!--    </condition>-->
<!--    <fail unless="java11">Java 11 runtime version is necessary to run this example</fail>-->


    <property name="module" location="${basedir}/${ant.project.name}"/>
    <property file="${basedir}/local_config.properties"/>

    <property name="src" location="${module}/src/main/java"/>
    <property name="resources" location="${module}/src/main/resources"/>
    <property name="lib_dir" value="${basedir}/../lib"/>
    <property name="build" location="${basedir}/../../build/${ant.project.name}"/>
    <property name="dist" location="${basedir}/../../dist"/>
    <property name="module_jar" value="${ant.project.name}.jar"/>
    <property name="Icons_jar" value="Icons.jar"/>
    <property name="Sounds_jar" value="Sounds.jar"/>

    <property name="properties" value="*.properties"/>

    <property name="classpath" value="
        ${lib_dir}/javaee.jar:
        ${lib_dir}/ez-vcard-0.9.5.jar:
        ${lib_dir}/jcommander-1.27.jar:
        ${lib_dir}/jpatterns-0.1.jar:
        ${lib_dir}/log4j-1.2-api-2.13.3.jar:
        ${lib_dir}/log4j-api-2.13.3.jar:
        ${lib_dir}/log4j-core-2.13.3.jar:
        ${lib_dir}/velocity-1.7-dep.jar:
    "/>

    <!--    Tests-->
    <property name="tests_dir" value="${module}/src/test"/>
    <property name="build_tests" location="${basedir}/../../build/${ant.project.name}_tests"/>
    <property name="test_resources" location="${module}/src/test/resources"/>
    <property name="build.test.results.dir" value="/tmp/test_results"/>
    <taskdef resource="testngtasks" classpath="${lib_dir}/testng-6.8.8.jar"/>
    <property name="test_classpath" value="
        ${lib_dir}/testng-6.8.8.jar:
        ${lib_dir}/hamcrest-all-1.3.jar:
        ${lib_dir}/awaitility-3.1.6.jar:
    "/>

    <target name="_init">
        <tstamp/>
        <mkdir dir="${build}"/>
        <mkdir dir="${dist}"/>
        <mkdir dir="${build_tests}"/>

        <copy todir="${build}" preservelastmodified="true">
            <fileset dir="${resources}" includes="${properties}"/>
            <fileset file="${resources}/images/Please_stand_by.png"/>
            <fileset file="${resources}/Magic.magic"/>
            <fileset file="${src}/org/pclg/tools/Clean.properties"/>
            <fileset file="${src}/org/pclg/tools/Clean.targets"/>
        </copy>

        <copy todir="${dist}" preservelastmodified="true">
            <fileset dir="${resources}" includes="${properties}"/>
            <fileset file="${resources}/images/Please_stand_by.png"/>
            <fileset file="${resources}/Magic.magic"/>
            <fileset file="${src}/org/pclg/tools/Clean.properties"/>
            <fileset file="${src}/org/pclg/tools/Clean.targets"/>
        </copy>
    </target>

    <target name="_compile" depends="_init" description="Compile the sources">
        <javac
                classpath="${classpath}"
                modulepath="${classpath}"
                includeantruntime="false"
                srcdir="${src}"
                destdir="${build}"
                deprecation="on"
                debug="true"
                verbose="no"
                listfiles="yes"
                source="${local_config.jdk-version}"
                target="${local_config.jdk-version}"
                encoding="ISO-8859-1">
            <compilerarg value="-Xlint"/>
        </javac>
    </target>

    <target name="_compile_tests" depends="_compile"
            description="compile the tests ">
        <javac
                classpath="${test_classpath} : ${classpath} : ${build}"
                includeantruntime="false"
                srcdir="${tests_dir}"
                destdir="${build_tests}"
                deprecation="on"
                debug="true"
                verbose="no"
                listfiles="yes"
                source="${local_config.jdk-version}"
                target="${local_config.jdk-version}"
                encoding="ISO-8859-1">
            <compilerarg value="-Xlint"/>
        </javac>
    </target>

    <target name="_tests" depends="_compile_tests">
        <testng failureProperty="test.failed" dumpCommand="true" outputdir="${build.test.results.dir}">
            <classpath>
                <path path="${test_resources} : ${test_classpath} : ${classpath} : ${build} : ${dist}"/>
            </classpath>
            <classpath location="${build_tests}"/>
            <classpath location="${tests_dir}"/>

            <classfileset dir="${build_tests}" includes="**/*Test*.class"/>

        </testng>
        <fail message="Test failure detected, check test results." if="test.failed"/>
    </target>

    <target name="module_jar" depends="_compile">
        <jar destfile="${dist}/${module_jar}" basedir="${build}" excludes="**">
            <fileset dir="${build}" includes="**/*.class"/>
            <manifest>
                <attribute name="Built-By" value="${user.name}"/>
                <attribute name="Class-Path" value="log4j-api-2.13.3.jar : log4j-core-2.13.3.jar : ."/>
            </manifest>
        </jar>
    </target>

    <target name="Icons_jar">
        <jar destfile="${dist}/${Icons_jar}"
             excludes="**">
            <fileset dir="${resources}" includes="images/Please_stand_by_2.png"/>
            <fileset dir="${resources}" includes="images/Please_stand_by.png"/>
            <fileset dir="${resources}" includes="images/unknown-**"/>
            <fileset dir="${resources}" includes="images/128x128/**"/>
            <fileset dir="${resources}" includes="images/48x48/**"/>
            <fileset dir="${resources}" includes="images/32x32/**"/>
            <fileset dir="${resources}" includes="images/24x24/**"/>
            <fileset dir="${resources}" includes="images/16x16/**"/>

            <fileset dir="${resources}"
                     includes="
					images/create.gif
					images/mars.gif
					images/question.gif
					images/romb-cyan.gif
					images/romb-red.gif
					images/romb-violet.gif
					images/zero.gif
				"/>

            <manifest>
                <attribute name="Built-By" value="${user.name}"/>
            </manifest>
        </jar>
    </target>

    <target name="Sounds_jar">
        <jar destfile="${dist}/${Sounds_jar}"
             excludes="**">
            <fileset dir="${resources}" includes="sounds/sbcdrop.wav"/>
            <fileset dir="${resources}" includes="sounds/success_sound.wav"/>

            <manifest>
                <attribute name="Built-By" value="${user.name}"/>
            </manifest>
        </jar>
    </target>

    <target name="build" depends="_tests, module_jar, Icons_jar, Sounds_jar"/>

     <target name="clean">
         <echo message="Cleaning ${ant.project.name}"/>
         <delete includeEmptyDirs="true">
             <fileset dir="${build}" includes="*/**"/>
         </delete>
         <delete includeEmptyDirs="true">
             <fileset dir="${build_tests}" includes="*/**"/>
         </delete>
    </target>
</project>