##La lista, separada por '|' de los archivos o directorios a agregar al
#classpath the la aplicaci�n.
FortunesDb.ClassPath=derby.jar

#Configuaci�n para Derby
FortunesDb.driver=org.apache.derby.jdbc.EmbeddedDriver
FortunesDb.url=jdbc:derby:/home/pablo/databases/fortunesDB;create=false

#Directory containing the fortune files (used by the loader)
FortunesDb.sourceDir=/home/pablo/development/projects/Alles/src/fortunes
