#Nombre del menu y nombre de la clase del L&F
#
#Mon Aug 21 18:02:09 CEST 2017
javax.swing.plaf.metal.MetalLookAndFeel=&Java Look'n'Feel
com.incors.plaf.kunststoff.KunststoffLookAndFeel=&Kunststoff Look'n'Feel
com.nilo.plaf.nimrod.NimRODLookAndFeel=NimRODLookAndFeel
net.beeger.squareness.SquarenessLookAndFeel=SquarenessLookAndFeel
de.muntjak.tinylookandfeel.TinyLookAndFeel=TinyLookAndFeel
com.digitprop.tonic.TonicLookAndFeel=TonicLookAndFeel
