#The following table defines the log levels and messages in log4j, in decreasing order of severity.
#The left column lists the log level designation in log4j and the right column provides a brief description of each log level.
#Level		Description
#OFF			The highest possible rank and is intended to turn off logging.
#FATAL		Severe errors that cause premature termination. Expect these to be immediately visible on a status console.
#ERROR		Other runtime errors or unexpected conditions. Expect these to be immediately visible on a status console.
#WARN		Use of deprecated APIs, poor use of API, 'almost' errors, other runtime situations that are undesirable
#				or unexpected, but not necessarily "wrong". Expect these to be immediately visible on a status console.
#INFO		Interesting runtime events (startup/shutdown). Expect these to be immediately visible on a console,
#				so be conservative and keep to a minimum.
#DEBUG		Detailed information on the flow through the system. Expect these to be written to logs only.
#TRACE		Most detailed information. Expect these to be written to logs only. Since version 1.2.12.[5]

# Root logger option
log4j.rootLogger=WARN, file, stdout

# Direct log messages to a log file
log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.File=/tmp/logs/log4j.log
log4j.appender.file.MaxFileSize=1MB
log4j.appender.file.MaxBackupIndex=20
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%M(%L) - %m%n

# Direct log messages to stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%-5p %c{1}:%L - %m%n

##########################  Agenda  ##########################
########################## Log de toda la aplicacion
log4j.category.org.pclg.agenda=WARN
log4j.category.org.pclg.tools=WARN

########################## Esto est� bastante probado, as� que s�lo quiero ver los errores
log4j.category.org.pclg.agenda.datasource=WARN
log4j.category.org.pclg.agenda.jdbc.AgendaDbJDBC=WARN
log4j.category.org.pclg.agenda.gui.AgendaGUI=WARN
log4j.category.org.pclg.agenda.entities.AgendaRecordImpl=WARN
log4j.category.org.pclg.agenda.entities.AgendaRecordTest=WARN
log4j.category.org.pclg.agenda.AgendaRecordUtil=WARN
log4j.category.org.pclg.agenda.AgendaUtil=DEBUG
log4j.category.org.pclg.agenda.gui.FileSystemView=WARN
log4j.category.org.pclg.agenda.plugins.CheckAndCopyPhotosPlugin=WARN

########################## Aqu� por lo general estoy experimentando, as� que mejor que si
log4j.category.org.pclg.agenda.plugins=TRACE

########################## Esto no me interesa de momento (salvo si es grave)
log4j.category.org.pclg.dbutil.VersatileConnection=WARN
log4j.category.org.pclg.dbutil.VersatilePreparedStatement=WARN
log4j.category.org.pclg.dbutil.VersatileResultSet=WARN

log4j.category.org.pclg.fortunes.Manager=WARN

log4j.category.org.pclg.security=WARN
log4j.category.org.pclg.security.Digest=WARN

log4j.category.org.pclg.tools.ImageTools=WARN
log4j.category.org.pclg.tools.FileTools=WARN
log4j.category.org.pclg.tools.ObservableProperties=WARN

log4j.category.org.pclg.xtras.ClassPathHacker=WARN

log4j.category.org.pclg.media=WARN
log4j.category.org.pclg.condominio=DEBUG

log4j.category.org.pclg.gui.JLabeledFieldGroup=WARN
log4j.category.org.pclg.tools.GUITools=WARN
log4j.category.org.pclg.gui=WARN
log4j.category.org.pclg.runtime.ProcessLauncher=WARN
log4j.category.org.pclg.runtime.JavaShellFX=DEBUG
log4j.category.CatPDFs=DEBUG

log4j.category.org.pclg.filesystem.synchonizer=WARN
log4j.category.org.pclg.filesystem.synchonizer.DirectorySynchronizer=WARN
