#The following table defines the log levels and messages in log4j, in decreasing order of severity.
#The left column lists the log level designation in log4j and the right column provides a brief description of each log level.
#Level		Description
#OFF			The highest possible rank and is intended to turn off logging.
#FATAL		Severe errors that cause premature termination. Expect these to be immediately visible on a status console.
#ERROR		Other runtime errors or unexpected conditions. Expect these to be immediately visible on a status console.
#WARN		Use of deprecated APIs, poor use of API, 'almost' errors, other runtime situations that are undesirable
#				or unexpected, but not necessarily "wrong". Expect these to be immediately visible on a status console.
#INFO		Interesting runtime events (startup/shutdown). Expect these to be immediately visible on a console,
#				so be conservative and keep to a minimum.
#DEBUG		Detailed information on the flow through the system. Expect these to be written to logs only.
#TRACE		Most detailed information. Expect these to be written to logs only. Since version 1.2.12.[5]

#The level of internal Log4j events that should be logged to the console.
# Valid values for this attribute are "trace", "debug", "info", "warn", "error" and "fatal".
status = error
#Either "err" for stderr, "out" for stdout, a file path, or a URL.
dest = err
name = PropertiesConfig

property.filename = /tmp/logs/log4j-new-try.log

filter.threshold.type = ThresholdFilter
filter.threshold.level = DEBUG

appender.rolling.type = RollingFile
appender.rolling.name = RollingFile
appender.rolling.fileName = ${filename}
appender.rolling.filePattern = /tmp/logs/log4j2-rolling.filePattern-%d{MM-dd-yy}-%i.log
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d %p %C{1.} [%t] %m%n
appender.rolling.policies.type = Policies
appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
# As Abid mentioned, interval value is interpreted in context of pattern that is specified as
# part of filePattern. It starts with lowest denomination. For example,if pattern contains S, frequency will be in millisecond.
# It supports the date pattern as described in detail as part of SimpleDateFormat java doc
# http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
appender.rolling.policies.time.interval = 2
appender.rolling.policies.time.modulate = true
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size=100MB
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 5

rootLogger.level = info
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.rolling.ref = RollingFile

# Root logger option
log4j.rootLogger=WARN, file, stdout

# Direct log messages to a log file
log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.File=/tmp/logs/log4j.appender.file.File.log
log4j.appender.file.MaxFileSize=1MB
log4j.appender.file.MaxBackupIndex=20
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd} %-5p %c{1}:%M(%L) - %m%n

# Direct log messages to stdout
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %-5p %c{1}:%L - %m%n
appender.console.filter.threshold.type = ThresholdFilter
appender.console.filter.threshold.level = debug

##########################  root package in pclg-apps module  ##########################
logger.pclg-root.name = org.pclg.root
logger.pclg-root.level = warn
logger.pclg-root.additivity = false
logger.pclg-root.appenderRef.rolling.ref = RollingFile
#logger.pclg-root.appenderRef.console.ref = LogToConsole
logger.pclg-root.appenderRef.console.ref = STDOUT

##########################  Portfolio  ##########################
logger.portfolio.name = org.pclg.finance.portfolio
logger.portfolio.level = trace
logger.portfolio.additivity = true
logger.portfolio.appenderRef.rolling.ref = RollingFile

logger.portfolio-persistence.name = org.pclg.finance.portfolio.persistence
logger.portfolio-persistence.level = trace
logger.portfolio-persistence.additivity = true
#logger.portfolio-persistence.appenderRef.rolling.ref = RollingFile

##########################  Agenda  ##########################
logger.agenda.name = org.pclg.agenda
logger.agenda.level = WARN
logger.agenda.additivity = true
logger.agenda.appenderRef.rolling.ref = RollingFile


##########################  pclg.tools  ##########################
logger.tools.name = org.pclg.tools
logger.tools.level = WARN
logger.tools.additivity = true
logger.tools.appenderRef.rolling.ref = RollingFile

########################## Esto estï¿½ bastante probado, asï¿½ que sï¿½lo quiero ver los errores
log4j.category.org.pclg.agenda.datasource=WARN
log4j.category.org.pclg.agenda.jdbc.AgendaDbJDBC=WARN
log4j.category.org.pclg.agenda.gui.AgendaGUI=WARN
log4j.category.org.pclg.agenda.entities.AgendaRecordImpl=WARN
log4j.category.org.pclg.agenda.entities.AgendaRecordTest=WARN
log4j.category.org.pclg.agenda.AgendaRecordUtil=WARN
log4j.category.org.pclg.agenda.AgendaUtil=DEBUG
log4j.category.org.pclg.agenda.gui.FileSystemView=WARN
log4j.category.org.pclg.agenda.plugins.CheckAndCopyPhotosPlugin=WARN

########################## Aquï¿½ por lo general estoy experimentando, asï¿½ que mejor que si
log4j.category.org.pclg.agenda.plugins=TRACE

########################## Esto no me interesa de momento (salvo si es grave)
log4j.category.org.pclg.dbutil.VersatileConnection=WARN
log4j.category.org.pclg.dbutil.VersatilePreparedStatement=WARN
log4j.category.org.pclg.dbutil.VersatileResultSet=WARN

log4j.category.org.pclg.fortunes.Manager=WARN

log4j.category.org.pclg.security=WARN
log4j.category.org.pclg.security.Digest=WARN

log4j.category.org.pclg.tools.ImageTools=WARN
log4j.category.org.pclg.tools.FileTools=WARN
log4j.category.org.pclg.tools.ObservableProperties=WARN

log4j.category.org.pclg.xtras.ClassPathHacker=WARN

log4j.category.org.pclg.media=WARN
log4j.category.org.pclg.condominio=DEBUG

log4j.category.org.pclg.gui.JLabeledFieldGroup=WARN
log4j.category.org.pclg.tools.GUITools=WARN
log4j.category.org.pclg.gui=WARN
log4j.category.org.pclg.runtime.ProcessLauncher=WARN
log4j.category.org.pclg.runtime.JavaShellFX=DEBUG
log4j.category.CatPDFs=DEBUG

log4j.category.org.pclg.filesystem.synchonizer=WARN
log4j.category.org.pclg.filesystem.synchonizer.DirectorySynchronizer=WARN
erRef.rolling.ref = RollingFile

logger.VersatileResultSet.name = org.pclg.dbutil.VersatileResultSet
logger.VersatileResultSet.level = trace
logger.VersatileResultSet.additivity = true
#logger.VersatileResultSet.appenderRef.rolling.ref = RollingFile


########################## Esto no me interesa de momento (salvo si es grave)
logger.dbutil.name = org.pclg.dbutil
logger.dbutil.level = WARN
logger.dbutil.additivity = true
#logger.dbutil.appenderRef.rolling.ref = RollingFile
logger.dbutil.appenderRef.stdout.ref = STDOUT

logger.VersatileConnection.name = org.pclg.dbutil.VersatileConnection
logger.VersatileConnection.level = WARN
logger.VersatileConnection.additivity = false
#logger.VersatileConnection.appenderRef.rolling.ref = RollingFile

logger.VersatilePreparedStatement.name = org.pclg.dbutil.VersatilePreparedStatement
logger.VersatilePreparedStatement.level = TRACE
logger.VersatilePreparedStatement.additivity = false
#logger.VersatilePreparedStatement.append


############################## FIXME: Esto no furula
logger.zoicapital.name = com.zoicapital.stockchartsfx
logger.zoicapital.level = error
logger.zoicapital.additivity = true
#logger.zoicapital.appenderRef.rolling.ref = RollingFile
