#
# Source configuration
#
dataSource=net.asintec.migrator.DataSourceJDBC
sourceDriverName=org.apache.derby.jdbc.EmbeddedDriver
sourceDbURL=jdbc:derby:/home/pablo/databases/agendaDB;create=false;dataEncryption=true;collation=TERRITORY_BASED:PRIMARY;bootPassword=XXX
sourceDatabase=null
sourceTable=CONTACTOS
#
# Target configuration
#
dataSink=net.asintec.migrator.DataSourceJDBC
targetDriverName=org.apache.derby.jdbc.EmbeddedDriver
targetDbURL=jdbc:derby:/tmp/_Agenda/agendaDB;create=true;dataEncryption=true;collation=TERRITORY_BASED:PRIMARY;bootPassword=XXX
targetTable=CONTACTOS
#
# Fields correspondence
#
CLAVE|CLAVE||||
VERSION|VERSION||||
DELETED|DELETED||||
NOMBRE|NOMBRE||||
APELLIDO|APELLIDO||||
SEXO|SEXO||||
PAIS|PAIS||||
VERSIONTELEFONO|VERSIONTELEFONO||||
VERSIONDIRECCION|VERSIONDIRECCION||||
VERSIONEMAIL|VERSIONEMAIL||||
VERSIONGRUPO|VERSIONGRUPO||||
VERSIONIMAGEN|VERSIONIMAGEN||||
VERSIONNOTAS|VERSIONNOTAS||||
DIA|DIA||||
MES|MES||||
ANO|ANO||||
MARCA|MARCA||||
FECHAACTUALIZACION|FECHAACTUALIZACION||||
FECHACREACION|FECHACREACION||||
LISTAR|LISTAR||||
