#
# Source configuration
#
dataSource=org.pclg.migrator.clarion.DataSourceClarion
sourceDriverName=null
sourceDbURL=null
sourceDatabase=C:\home\development\modules\src\clarion\DATOS\sistema
sourceTable=Fortune.DAT
#
# Target configuration
#
dataSink=net.asintec.migrator.DataSourceJDBC
targetDriverName=org.apache.derby.jdbc.EmbeddedDriver
targetDbURL=jdbc:derby:C:/_Agenda/agendaDB;create=false
targetTable=FORTUNES
#
# Fields correspondence
#
CLAVE|||||
FORTUNE|FORTUNE||org.pclg.migrator.clarion.PreprocessorClarionMemo|60:12|
