#
# Source configuration
#
#dataSource=net.asintec.migrator.DataSourceJDBC
#sourceDriverName=org.gjt.mm.mysql.Driver
#sourceDbURL=jdbc:mysql://localhost/agenda
#sourceTable=contactos

dataSource=org.pclg.migrator.clarion.DataSourceClarion
sourceDatabase=C:\tmp
sourceTable=FECHAS.DAT

#
# Target configuration
#
dataSink=net.asintec.migrator.DataSinkJDBC
targetDriverName=org.apache.derby.jdbc.EmbeddedDriver
targetDbURL=jdbc:derby:C:/tmp/agenda_test/agendaTest;create=true
targetTable=contactos_kk
#
# Fields correspondence
#
Clave|Clave||||
Version|Version||||
Deleted|Deleted||||
Nombre|Nombre||||
Apellido|Apellido||||
Direccion|Direccion||||
Imagen|Imagen||||
Sexo|Sexo||||
Pais|Pais||||
Email|Email||||
Dia|Dia||||
Mes|Mes||||
Ano|Ano||||
Marca|Marca||||
FechaActualizacion|FechaActualizacion||||
FechaCreacion|FechaCreacion||||
Listar|Listar||||
Notas|Notas||||
VersionTelefono|VersionTelefono||||
