#
# Source configuration
#
dataSource=net.asintec.migrator.DataSourceJDBC
sourceDriverName=org.gjt.mm.mysql.Driver
sourceDbURL=jdbc:mysql://localhost/agenda
sourceTable=telefonos_cr
#
# Target configuration
#
dataSink=net.asintec.migrator.DataSourceJDBC
targetDriverName=org.gjt.mm.mysql.Driver
targetDbURL=jdbc:mysql://localhost/agenda
targetTable=telefonos
#
# Fields correspondence
#
Clave|Clave||||
Version|Version||||
Secuencia|Secuencia||||
Numero|Numero||org.pclg.agenda.crypto.PreprocessorCryptString||
