#
# Source configuration
#
dataSource=net.asintec.migrator.DataSourceJDBC
sourceDriverName=org.gjt.mm.mysql.Driver
sourceDbURL=jdbc:mysql://localhost/agenda
sourceTable=contactos
#
# Target configuration
#
dataSink=net.asintec.migrator.DataSourceJDBC
targetDriverName=org.apache.derby.jdbc.EmbeddedDriver
targetDbURL=jdbc:derby:C:/tmp/agenda/agendaDB;create=true
targetTable=contactos
#
# Fields correspondence
#
Clave|Clave||||
Version|Version||||
Deleted|Deleted||||
Nombre|Nombre||||
Apellido|Apellido||||
Direccion|Direccion||||
Imagen|Imagen||||
Sexo|Sexo||||
VersionTelefono|VersionTelefono||||
Pais|Pais||||
Email|Email||||
Dia|Dia||||
Mes|Mes||||
Ano|Ano||||
Marca|Marca||||
FechaActualizacion|FechaActualizacion||||
FechaCreacion|FechaCreacion||||
Listar|Listar||||
Notas|Notas||||
