RENAME TABLE Root.TELEFONOS TO TELEFONO;
RENAME TABLE Root.CONTACTOS TO CONTACTO;
RENAME TABLE Root.PAISES TO PAIS;
RENAME TABLE Root.NOTAS TO NOTA;
DROP TABLE Root.DIRECCION_OLD;

UPDATE Root.Contacto SET versionTelefono = 0 WHERE versionTelefono IS NULL;
UPDATE Root.Contacto SET versionDireccion = 0 WHERE versionDireccion IS NULL;
UPDATE Root.Contacto SET versionEmail = 0 WHERE versionEmail IS NULL;
UPDATE Root.Contacto SET versionGrupo = 0 WHERE versionGrupo IS NULL;
UPDATE Root.Contacto SET versionImagen = 0 WHERE versionImagen IS NULL;
UPDATE Root.Contacto SET versionNotas = 0 WHERE versionNotas IS NULL;

ALTER TABLE Root.CONTACTO ALTER COLUMN versionTelefono NOT NULL;
ALTER TABLE Root.CONTACTO ALTER COLUMN versionDireccion NOT NULL;
ALTER TABLE Root.CONTACTO ALTER COLUMN versionEmail NOT NULL;
ALTER TABLE Root.CONTACTO ALTER COLUMN versionGrupo NOT NULL;
ALTER TABLE Root.CONTACTO ALTER COLUMN versionImagen NOT NULL;
ALTER TABLE Root.CONTACTO ALTER COLUMN versionNotas NOT NULL;
ALTER TABLE Root.CONTACTO ALTER COLUMN listar NOT NULL;
ALTER TABLE Root.CONTACTO ALTER COLUMN ano NOT NULL;
ALTER TABLE Root.CONTACTO ALTER COLUMN mes NOT NULL;
ALTER TABLE Root.CONTACTO ALTER COLUMN dia NOT NULL;
ALTER TABLE Root.CONTACTO ALTER COLUMN pais NOT NULL;
ALTER TABLE Root.CONTACTO ALTER COLUMN sexo NOT NULL;

ALTER TABLE Root.CONTACTO DROP PRIMARY KEY;

ALTER TABLE Root.TELEFONO DROP CONSTRAINT Tipos_FK;

ALTER TABLE Root.CONTACTO ADD CONSTRAINT CONTACTO_PK PRIMARY KEY (Clave, Version);
ALTER TABLE Root.CONTACTO ADD FOREIGN KEY (PAIS) References root.PAIS(CODIGO);

ALTER TABLE Root.TELEFONO ADD FOREIGN KEY (tipo) References root.TipoTELEFONO(clave);

UPDATE Root.Control SET FechaActualizacion = CURRENT_TIMESTAMP;
