flgspain1.image=/toolbarButtonGraphics/flgspain1.gif
mars.image=/images/mars.gif
stop.image=/toolbarButtonGraphics/general/Stop16.gif
espanaRepublicana.image=/toolbarButtonGraphics/es-rep.gif
deutschland.image=/toolbarButtonGraphics/deutschland.gif
uk.image=/toolbarButtonGraphics/uk.gif
france.image=/toolbarButtonGraphics/france.gif
new.image=/toolbarButtonGraphics/general/New24.gif
stop24.image=/toolbarButtonGraphics/general/Stop24.gif
undo24.image=/toolbarButtonGraphics/general/Undo24.gif
question.image=/images/question.gif
redo.image=/toolbarButtonGraphics/general/Redo24.gif
zero.image=/images/zero.gif
