# Las claves que comienzan con 'EXT_' son los recursos para las distintas
# extensiones de los archivos
#EXT_dat=Datos@#@/images/gopher-binary.gif
#EXT_gif=Imagen GIF@#@/images/gifIcon.gif
#EXT_ico=Icono@#@/images/edit.gif
#EXT_jar=Java archive@#@/images/Jar16.gif
#EXT_jpg=Imagen JPEG@#@/images/jpgIcon.jpg
#EXT_jude=Diagrama UML de Jude@#@/images/jude-doc.jpg
#EXT_log=Registro de actividades@#@/images/doc.gif
#EXT_png=Imagen JPEG@#@/images/jpgIcon.jpg
#EXT_properties=Configuracion de aplicacion@#@/images/doc.gif
#EXT_txt=Documento de texto@#@/images/doc.gif
no_access_dir=D:/plucien/Reise/agenda/org
error_obteniendo_recursos = Error obteniendo recursos para clave {0}.