dataSource=net.asintec.migrator.DataSourceJDBC
dataSink=net.asintec.migrator.DataSinkJDBC
sourceDatabase=C:\home\databases\FileDataBase.mdb
targetDatabase=C:\home\databases\FileDataBaseVacia.mdb
sourceTable=Directorios
targetTable=Directorios
Codigo|Codigo||||
Nombre|Camino||||
