DROP TABLE FORTUNES;

CREATE TABLE FORTUNES (
	Clave INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0 ,INCREMENT BY 1),
	Fortune LONG VARCHAR NOT NULL
);

INSERT INTO FORTUNES (FORTUNE) VALUES ('');
