##SQLs para la inicializacion de la aplicación

# suppress inspection "UnusedProperty" for whole file

#La lista, separada por ';' de las tablas de la aplicación.
#Al crear las tablas se ejecutan todas las sentencias AgendaDb.create<tabla> y
#AgendaDb.populate<tabla>, AgendaDb.createINDEX_<tabla>?
#y eventualmente DROP TABLE <tabla>
#AgendaDb.tables=CONTROL;TipoTelefono;TELEFONO;DIRECCION;EMAIL;IMAGEN;NOTA;PAIS;NOMBRES;CONTACTO;ContactoNOMBRE;ContactoApellido;GRUPO;ContactoGrupo
AgendaDb.tables=CONTROL;PAIS;TipoTelefono;TELEFONO;DIRECCION;EMAIL;IMAGEN;NOTA;CONTACTO;GRUPO;ContactoGrupo

#Las sentencias para crear las tablas
# ¿Poner nombre y apellido en tablas aparte? Puede merecer la pena.
#AgendaDb.createNOMBRES=CREATE TABLE NOMBRES (\
#	Clave INTEGER PRIMARY KEY,\
#	NOMBRE VARCHAR(15) NOT NULL\
#)
#
#AgendaDb.createContactoNOMBRE=CREATE TABLE ContactoNOMBRE (\
#	Clave INTEGER NOT NULL,\
#	Version INTEGER NOT NULL,\
#   Secuencia INTEGER NOT NULL,\
#	ClaveNOMBRE INTEGER NOT NULL,\
#	PRIMARY KEY (Clave, Version, Secuencia)\
#)
#
#AgendaDb.createContactoApellido=CREATE TABLE ContactoApellido (\
#	Clave INTEGER NOT NULL,\
#	Version INTEGER NOT NULL,\
#   Secuencia INTEGER NOT NULL,\
#	ClaveNOMBRE INTEGER NOT NULL,\
#	PRIMARY KEY (Clave, Version, Secuencia)\
#)

AgendaDb.createCONTACTO=CREATE TABLE CONTACTO (\
	Clave INTEGER NOT NULL,\
	Version INTEGER NOT NULL,\
	Deleted BOOLEAN NOT NULL DEFAULT FALSE,\
	Nombre VARCHAR(30),\
	Apellido VARCHAR(30),\
	Sexo VARCHAR(1) NOT NULL,\
	Pais VARCHAR(3) NOT NULL CONSTRAINT CONTACTO_PAIS_FK References PAIS(CODIGO),\
	VersionTelefono INTEGER NOT NULL DEFAULT 0,\
	VersionDireccion INTEGER NOT NULL DEFAULT 0,\
	VersionEmail INTEGER NOT NULL DEFAULT 0,\
	VersionGrupo INTEGER NOT NULL DEFAULT 0,\
	VersionImagen INTEGER NOT NULL DEFAULT 0,\
	VersionNotas INTEGER NOT NULL DEFAULT 0,\
	Dia INTEGER NOT NULL DEFAULT 0,\
	Mes INTEGER NOT NULL DEFAULT 0,\
	Ano INTEGER NOT NULL DEFAULT 0,\
	Marca VARCHAR(2),\
	FechaActualizacion TIMESTAMP,\
	FechaCreacion TIMESTAMP,\
	Listar BOOLEAN DEFAULT TRUE,\
    PRIMARY KEY (Clave, Version)\
)
#	VersionNombres INTEGER,\
#	VersionApellidos INTEGER,\
#ij> alter table root.contacto add VersionNombres INTEGER;
#ij> alter table root.contacto add VersionApellidos INTEGER;

AgendaDb.createINDEX_CONTACTO1=CREATE INDEX IDX_CONTACTO1 ON CONTACTO (NOMBRE, APELLIDO)
AgendaDb.createINDEX_CONTACTO2=CREATE INDEX IDX_CONTACTO2 ON CONTACTO (MARCA)
AgendaDb.createINDEX_CONTACTO3=CREATE INDEX IDX_CONTACTO3 ON CONTACTO (MES, DIA)
#AgendaDb.createINDEX_CONTACTO4=CREATE INDEX IDX_CONTACTO4 ON CONTACTO (FechaCreacion DESC)
#AgendaDb.createINDEX_CONTACTO5=CREATE INDEX IDX_CONTACTO5 ON CONTACTO (FechaActualizacion DESC)

AgendaDb.createGRUPO=CREATE TABLE GRUPO (\
	Clave INTEGER PRIMARY KEY,\
	NOMBRE VARCHAR(40) NOT NULL\
)

AgendaDb.populateGRUPO=INSERT INTO GRUPO VALUES\
	(1,'Familia'),\
	(2,'Amigos')

AgendaDb.createContactoGrupo=CREATE TABLE ContactoGrupo (\
	Clave INTEGER NOT NULL,\
	Version INTEGER NOT NULL,\
	Secuencia INTEGER NOT NULL,\
	ClaveGrupo INTEGER NOT NULL CONSTRAINT CONTACTOGRUPO_GRUPO_FK References GRUPO(Clave),\
	PRIMARY KEY (Clave, Version, Secuencia)\
)

AgendaDb.createPAIS=CREATE TABLE PAIS (\
	CODIGO VARCHAR(3) PRIMARY KEY,\
	NOMBRE VARCHAR(40) NOT NULL,\
	FORMATO_TELEFONO VARCHAR(20)\
)

AgendaDb.populatePAIS=INSERT INTO PAIS VALUES\
	('0','Erewhon', null),\
	('1','USA', '(###)###-##-##'),\
	('30','Grecia', null),\
	('33','France', '##.##.##.##.##'),\
	('34','España', '###.##.##.##'),\
	('351','Portugal',null),\
	('353','Eire','### ### ####'),\
	('36','Magyarorszßg','## ### ####'),\
	('39','Italia', null),\
	('41','Schweizerische Eidgenossenschaft','## ### ## ##'),\
	('420','Ceska republika',null),\
	('43','Österreich', null),\
	('44','England', null),\
	('46','Sverige', null),\
	('49','Deutschland', null),\
	('507','Panamá',null),\
	('52','Mexico', null),\
	('54','Argentina','# ## ####-####'),\
	('55','Brasil', null),\
	('56','Chile','# #### ####'),\
	('57','Colombia',null),\
	('58','Venezuela', '####.###.##.##'),\
	('7','Rusia', null)

AgendaDb.createTipoTelefono=CREATE TABLE TipoTelefono(\
    Clave INTEGER NOT NULL,\
	Nombre VARCHAR(20) NOT NULL,\
	ForeGroundColor INTEGER NOT NULL DEFAULT 0,\
    PRIMARY KEY (Clave)\
)

AgendaDb.populateTipoTelefono=INSERT INTO TipoTelefono VALUES\
	(1,'Fijo Movistar',65280),\
	(2,'Movil Movistar',255),\
	(3,'Vodafone',16711680),\
	(4,'Orange',16724736),\
	(5,'Yoigo',16729313),\
	(6,'Tuenti',4420939),\
	(7,'Simyo',16754965)

AgendaDb.createTELEFONO=CREATE TABLE TELEFONO(\
    Clave INTEGER NOT NULL,\
	Version INTEGER NOT NULL,\
    Secuencia INTEGER NOT NULL,\
    countryPrefix VARCHAR(3) NOT NULL CONSTRAINT TELEFONO_Pais_FK REFERENCES PAIS,\
	Numero VARCHAR(15) NOT NULL,\
    Tipo INTEGER CONSTRAINT TELEFONO_TipoTelefono_FK REFERENCES TipoTelefono,\
    PRIMARY KEY (Clave, Version, Secuencia)\
)

AgendaDb.createDIRECCION=CREATE TABLE DIRECCION(\
    Clave INTEGER NOT NULL,\
	Version INTEGER NOT NULL,\
    Secuencia INTEGER NOT NULL,\
	Direccion VARCHAR(100) NOT NULL,\
    PRIMARY KEY (Clave, Version, Secuencia)\
)

AgendaDb.createEMAIL=CREATE TABLE EMAIL(\
    Clave INTEGER NOT NULL,\
	Version INTEGER NOT NULL,\
    Secuencia INTEGER NOT NULL,\
	Email VARCHAR(100) NOT NULL,\
    PRIMARY KEY (Clave, Version, Secuencia)\
)

AgendaDb.createIMAGEN=CREATE TABLE IMAGEN(\
    Clave INTEGER NOT NULL,\
	Version INTEGER NOT NULL,\
	imagePath VARCHAR(260) NOT NULL,\
	thumbnail BLOB NOT NULL,\
    PRIMARY KEY (Clave, Version)\
)

AgendaDb.createNOTA=CREATE TABLE NOTA(\
    Clave INTEGER NOT NULL,\
	Version INTEGER NOT NULL,\
    Secuencia INTEGER NOT NULL,\
	Nota VARCHAR(150) NOT NULL,\
    PRIMARY KEY (Clave, Version, Secuencia)\
)

AgendaDb.createCONTROL=CREATE TABLE CONTROL(\
	FechaActualizacion TIMESTAMP\
)

AgendaDb.populateCONTROL=INSERT INTO CONTROL VALUES\
	(NULL)
