#Configuracion de Alter
#Fri Aug 03 17:24:01 CEST 2018
applicationBounds.h=931
applicationBounds.w=1893
applicationBounds.x=0
applicationBounds.y=0
Col0Pos=0
Col0Visible=true
Col0Width=33
Col1Pos=1
Col1Visible=true
Col1Width=560
Col2Pos=2
Col2Visible=true
Col2Width=479
Col3Pos=3
Col3Visible=true
Col3Width=31
errConsoleBounds.h=371
errConsoleBounds.w=334
errConsoleBounds.x=0
errConsoleBounds.y=0
FileListPanel.filter.item.0=.+\\.png|.+\\.jar
FileListPanel.filter.item.1=.+\\.jpg|.+\\.jar
FileListPanel.filter.item.2=.+\\.jar
FileListPanel.filter.item.3=.+\\.properties
FileListPanel.filter.item.6=.+1280x720.+\\.mp4|.+\\.jpg|.+\\.jpeg|.+\\.gif|.+\\.bmp|.+
lafName=net.beeger.squareness.SquarenessLookAndFeel
lafThemeName=javax.swing.plaf.metal.DefaultMetalTheme
lastFilter=.+\\.png|.+\\.jar
org.pclg.filesystem.DirQueue.cwdPointer=0
org.pclg.filesystem.DirQueue.dir0=C\:\\home\\development\\dist
org.pclg.filesystem.DirQueue.dir1=F\:\\Pel\u00EDculas\\Films
org.pclg.filesystem.DirQueue.queueSize=2
splitPane.lastDividerLocation=412
