<project name="pclg-apps" default="_dist" basedir="../../../..">

    <description>Builds pclg apps</description>

    <property name="module" location="${basedir}/${ant.project.name}"/>
    <property file="${basedir}/local_config.properties"/>

    <property name="img_dir" value="${basedir}/pclg-tools/src/main/resources/images"/>  <!-- FIXME: this don't belongs here   -->
    <!-- set global properties for this build -->

    <property file="${basedir}/local_config.properties"/>

    <property name="src" location="${module}/src/main/java"/>
    <property name="config_dir" location="${module}/src/main/config"/>
    <property name="properties" value="ProcessLauncher*.properties FileView.properties"/>
    <property name="lib_dir" value="${basedir}/../lib"/>
    <property name="libLAF_dir" value="${basedir}/../lib_L&amp;F"/>
    <property name="libNoJ11_dir" value="${basedir}/../libs-que-causan-problemas-en-J11"/>
    <property name="resources" location="${module}/src/main/resources"/>
    <property name="java_home" location="C:/usr/local/Java/jdk/current"/>
    <property name="build" location="${basedir}/../../build/${ant.project.name}"/>
    <property name="build_tests" location="${basedir}/../../classes_tests"/>
    <property name="dist" location="${basedir}/../../dist"/>
    <property name="docs_dir" location="${basedir}/../../docs"/>
    <property name="JDK_API_dir" location="${java_home}/docs/api"/>
    <property name="clear_lukas_jar_name" value="${dist}/Lukas.jar"/>
    <property name="classpath" value="
        ${lib_dir}/gnu.getopt.jar:
        ${lib_dir}/itextpdf-5.3.4.jar:
        ${lib_dir}/ez-vcard-0.9.5.jar:
        ${lib_dir}/jxl.jar:
        ${lib_dir}/log4j-1.2-api-2.13.3.jar:
        ${lib_dir}/log4j-api-2.13.3.jar:
        ${lib_dir}/log4j-core-2.13.3.jar:

        ${libLAF_dir}/kunststoff.jar:

        ${libNoJ11_dir}/jdom-1.0.jar:

        ${dist}/pclg-tools.jar:
        "/>

    <!--    Tests-->
    <property name="tests_dir" value="${module}/src/test"/>
    <property name="build_tests" location="${basedir}/../../build/${module-name}_tests"/>
    <property name="test_resources" location="${module}/src/test/resources"/>
    <property name="build.test.results.dir" value="/tmp/test_results"/>
    <taskdef resource="testngtasks" classpath="${lib_dir}/testng-6.8.8.jar"/>
    <property name="test_classpath" value="
        ${lib_dir}/testng-6.8.8.jar:
        ${lib_dir}/jcommander-1.27.jar:
    "/>

    <target name="_info">
        <echo>
            This script builds all the everything of the (known) universe

            Relevant targets:
            dist build everything
            compile
            Lukas
            docs build API docs for everything
            clean guess what...
            cleanAll guess what..., pero ademas la documentacion, ...
            info Presenta esta informacion
            solo por tocar los cataplines puse este
            target como default, en vez de 'dist'

        </echo>
    </target>

    <target name="_init">
        <!-- Create the time stamp -->
        <tstamp/>

        <!-- Create the build directory structure used by compile -->
        <mkdir dir="${build}"/>
        <mkdir dir="${build_tests}"/>
        <mkdir dir="${dist}"/>
        <mkdir dir="${docs_dir}"/>

        <!-- Copy the required libraries. -->
        <copy todir="${dist}" preservelastmodified="true">
            <fileset file="${lib_dir}/derby.jar"/>
            <fileset file="${libLAF_dir}/kunststoff.jar"/>
            <fileset file="${lib_dir}/gnu.getopt.jar"/>
            <fileset file="${lib_dir}/velocity-1.7-dep.jar"/>
            <fileset file="${lib_dir}/itextpdf-5.3.4.jar"/>
            <fileset file="${lib_dir}/jxl.jar"/>
            <fileset file="${lib_dir}/jid3lib-0.5.4.jar"/>
            <fileset file="${lib_dir}/log4j-api-2.13.3.jar"/>
            <fileset file="${lib_dir}/ez-vcard-0.9.5.jar"/>
            <fileset file="${lib_dir}/xalan-2.7.2.jar"/>
            <fileset file="${lib_dir}/docx4j-3.3.1.jar"/>
            <fileset file="${lib_dir}/serializer-2.7.2.jar"/>
            <fileset file="${lib_dir}/guava-18.0.jar"/>
            <fileset file="${lib_dir}/docx4j-3.3.1.jar"/>
            <fileset file="${lib_dir}/commons-io-1.3.2.jar"/>
            <fileset file="${lib_dir}/slf4j-api-1.7.7.jar"/>
            <fileset file="${lib_dir}/json-20180130.jar"/>
        </copy>

        <!-- Copiar los archivos necesarios al directorio dist -->
        <copy todir="${dist}" preservelastmodified="true">
            <fileset dir="${config_dir}" includes="${properties}"/>
            <fileset file="${src}/Dw.properties"/>
            <fileset file="${config_dir}/log4j.properties"/>
            <fileset file="${config_dir}/derby.properties"/>
        </copy>

        <!-- Copiar los archivos necesarios al directorio build -->
        <copy todir="${build}" preservelastmodified="true">
            <fileset dir="${config_dir}" includes="${properties}"/>
            <fileset file="${src}/Dw.properties"/>
            <fileset file="${src}/Skel.properties"/>
            <fileset file="${config_dir}/log4j.properties"/>
            <fileset file="${config_dir}/derby.properties"/>
        </copy>

        <copy file="${config_dir}/ProcessLauncher_technical-${local_config.host.name}.properties" tofile="${build}/ProcessLauncher_technical.properties" preservelastmodified="true"/>
        <copy file="${config_dir}/ProcessLauncher_technical-${local_config.host.name}.properties" tofile="${dist}/ProcessLauncher_technical.properties" preservelastmodified="true"/>
    </target>

    <target name="_compile" depends="_init" description="compile the source ">
        <!-- Compile the java code from ${src} into ${build} -->
        <javac
                classpath="${classpath}"
                modulepath="${classpath}"
                includeantruntime="false"
                srcdir="${src}"
                destdir="${build}"
                deprecation="on"
                debug="true"
                verbose="no"
                listfiles="yes"
                source="${local_config.jdk-version}"
                target="${local_config.jdk-version}"
                encoding="ISO-8859-1">
            <compilerarg value="-Xlint"/>
        </javac>
    </target>

    <target name="_compile_tests" depends="_compile"
            description="compile the tests ">
        <javac
                classpath="${test_classpath} : ${classpath} : ${build}"
                includeantruntime="false"
                srcdir="${tests_dir}"
                destdir="${build_tests}"
                deprecation="on"
                debug="true"
                verbose="no"
                listfiles="yes"
                source="${local_config.jdk-version}"
                target="${local_config.jdk-version}"
                encoding="ISO-8859-1">
            <compilerarg value="-Xlint"/>
        </javac>
    </target>

    <taskdef resource="testngtasks"
             classpath="${lib_dir}/testng-6.8.8.jar"/>

    <property name="build.test.results.dir" value="/tmp/test_results"/>
    <target name="_tests" depends="_compile_tests">
<!--        <testng failureProperty="test.failed" dumpCommand="true" outputdir="${build.test.results.dir}" haltOnfailure="false" configFailurePolicy="true">-->
        <testng failureProperty="test.failed" dumpCommand="true" outputdir="${build.test.results.dir}">
            <classpath>
                <path path="${test_resources} : ${test_classpath} : ${classpath} : ${build} : ${dist}"/>
            </classpath>
            <classpath location="${build_tests}"/>
            <classpath location="${tests_dir}"/>

            <classfileset dir="${build_tests}" includes="**/*Test*.class"/>

        </testng>
        <fail message="Test failure detected, check test results." if="test.failed"/>
    </target>

    <target name="_clean_dist" depends="clean, _dist"
            description="generate the distribution from scratch">
    </target>

    <target name="build" depends="_dist_unsafe" />

    <target name="_dist" depends="_tests, _dist_unsafe"
            description="generate the distribution">
    </target>

    <target name="_dist_unsafe" depends="_compile, Lukas_jar,
                ProcessLauncher_jar,
                OuvrirSuivi_jar,
                JavaShell_jar, JavaShellSwing_Deprecated_jar"
            description="generate the distribution WITHOUT THE TESTS!!!">

        <!-- Put everything in ${build} into the MyProject-${DSTAMP}.jar file -->
        <!--jar jarfile="${dist}/MyProject-${DSTAMP}.jar" basedir="${build}"/-->
    </target>

    <!-- Un jar con utilities para llevar por ahi -->
    <target name="Lukas_jar" depends="_compile" description="generar Lukas.jar">
        <jar destfile="${clear_lukas_jar_name}" basedir="${build}"
             excludes="**">
            <!-- Clases auxiliares -->
            <fileset dir="${build}"
                     includes="
				BigFileCreator*.class
				CatPDFs*.class
				Cr*.class
				Diff*.class
				Digest*.class
				DNI*.class
				Dw*.class
				ExpensesSorter*.class
				FilenameNormalizer*.class
				GetBlocks*.class
				Grep*.class
				Indexer*.class
				JWhich*.class
				MaestroFileConverter*.class
				Magic*.class
				Scanner*.class
				Splitter*.class
				Skel*.class
				Stega*.class
				Tabifier*.class
				WordWrap*.class
				dbinfo/SQLMessages*.class
				javaspecialists/ReflectionHelper*.class
				org/pclg/annotations/*.class
				org/pclg/dbutil/DbUpdate*.class
				org/pclg/filesystem/FileCreator*.class
				org/pclg/filesystem/FileSplitter*.class
				org/pclg/filesystem/fileattributes/*.class
				org/pclg/filesystem/Magic*.class
				org/pclg/filesystem/MagicEntry*.class
				org/pclg/filesystem/Touch*.class
				org/pclg/finance/funds/UpdateFundsExcel*.class
		 		org/pclg/gui/JLabeledField*.class
				org/pclg/gui/VersatileJMenu**.class
				org/pclg/log/*.class
				org/pclg/media/utils/SrtAdjuster*.class
				org/pclg/net/Dw*.class
				org/pclg/security/Crypto*.class
				org/pclg/security/Digest*.class
				org/pclg/security/Steganograph*.class
                org/pclg/tools/ArrayTools*.class
                org/pclg/tools/Chrono*.class
                org/pclg/tools/Clean*.class
                org/pclg/tools/ComponentMutator*.class
                org/pclg/tools/ConfigurableComparator*.class
                org/pclg/tools/Constants*.class
                org/pclg/tools/ControlableThread*.class
                org/pclg/tools/Crono*.class
                org/pclg/tools/DatabaseTools*.class
                org/pclg/tools/DigestTools*.class
                org/pclg/tools/ExtensionFiltro*.class
                org/pclg/tools/FileComparator*.class
                org/pclg/tools/FileTools*.class
                org/pclg/tools/GUITools**.class
                org/pclg/tools/LabeledComponent*.class
                org/pclg/tools/LengthControlledField*.class
                org/pclg/tools/PCLGTools*.class
                org/pclg/tools/PropertiesHelper*.class
                org/pclg/tools/SortedProperties*.class
                org/pclg/tools/StringTools*.class
                org/pclg/tools/ToolBox*.class
                org/pclg/tools/velocity/VelocityDriver*.class
		 		org/pclg/xtras/ClassPathHacker*.class
		 		org/pclg/xtras/ColorTable*.class
		 		org/pclg/xtras/Colortable*.class
			"/>

            <fileset dir="${src}"
                     includes="
				Magic.magic
				org/pclg/tools/Chrono.properties
				Dw.help
				ExpensesSorter.conf
				Skel.properties
				*.mdl
			"/>

            <fileset dir="${basedir}" includes="docs/**"/>
            <manifest>
                <attribute name="Built-By" value="${user.name}"/>
                <attribute name="Main-Class" value="org.pclg.tools.Clean"/>
                <attribute name="Class-Path"
                           value=". : pclg-tools.jar : velocity-1.7-dep.jar : gnu.getopt.jar : itextpdf-5.3.4.jar : jxl.jar : log4j-api-2.13.3.jar : log4j-core-2.13.3.jar"/>
                <section name="common/class1.class">
                    <attribute name="Sealed" value="false"/>
                </section>
            </manifest>
        </jar>
    </target>

    <target name="_docs" depends="_init" description="Genera la documentacion">
        <javadoc
                classpath="${lib_dir}"
                packagenames="*"
                sourcepath="${src}"
                destdir="${docs_dir}"
                author="true"
                version="true"
                private="true"
                windowtitle="Documentacion de tutto"
                linksource="yes">
            <!--use="true" no se puede usar debido al bug 6442980 -->

            <link href="file:///${JDK_API_dir}"/>

            <!--link href="file:///C|/pablo/java/packages/de/id3package/FILES/DOC/"/-->

            <fileset dir="${src}" casesensitive="yes">
                <!--include name="**/*.java"/     Esto incluye recursivamente -->
                <include name="*.java"/>
                <!--include name="pclg/*.java"/-->
                <exclude name="**/*Test*"/>
            </fileset>

        </javadoc>
    </target>

    <target name="clean" description="clean up">
        <delete includeEmptyDirs="true">
            <fileset dir="${build}" includes="**/**"/>
            <fileset dir="${build_tests}" includes="**/**"/>
            <fileset dir="${dist}" includes="**/pclg-*.jar"/>
            <fileset dir="${dist}" includes="**/net-asintec-*.jar"/>
        </delete>
    </target>


    <target name="_cleanAll" description="borrar todo, todito, todito"
            depends="clean">
        <delete dir="${docs_dir}"/>
    </target>


    <target name="Finance" depends="_compile" description="generar Finance">
        <jar destfile="${dist}/Finance.jar"
             basedir="${build}"
             includes="org/pclg/finance/**">
            <manifest>
                <attribute name="Built-By" value="${user.name}"/>
                <attribute name="Main-Class" value="org.pclg.finance.Main"/>
                <attribute name="Class-Path"
                           value="toolbarButtonGraphics.jar : ."/>
            </manifest>
        </jar>
    </target>


    <property name="OuvrirSuivi_jar_name" value="OuvrirSuivi.jar"/>
    <target name="OuvrirSuivi_jar" depends="_compile">
        <jar destfile="${dist}/${OuvrirSuivi_jar_name}" basedir="${build}"
             excludes="**">
            <fileset dir="${build}" includes="misc/sopra/OuvrirSuivi*.class"/>
            <fileset dir="${img_dir}" includes="dialog-question.png"/>
            <manifest>
                <attribute name="Built-By" value="${user.name}"/>
                <attribute name="Main-Class" value="misc.sopra.OuvrirSuivi"/>
                <attribute name="Class-Path" value="log4j-api-2.13.3.jar : log4j-core-2.13.3.jar"/>
            </manifest>
        </jar>
    </target>

    <property name="ProcessLauncher_jar_name" value="ProcessLauncher.jar"/>
    <target name="ProcessLauncher_jar" depends="_compile">
        <jar destfile="${dist}/${ProcessLauncher_jar_name}" basedir="${build}" excludes="**">
            <fileset dir="${build}" includes="
                org/pclg/runtime/ProcessLauncher*.class
                org/pclg/runtime/Executioner*.class
                org/pclg/filesystem/fileattributes/*.class
            	org/pclg/gui/InfoPanel*.class
            	org/pclg/gui/JLabeledField*.class
            	org/pclg/gui/VersatileJMenu*.class
            	org/pclg/security/Crypto*.class
            	org/pclg/security/PasswordDialog*.class
            	org/pclg/log/*.class
                org/pclg/tools/Changeable*.class
                org/pclg/tools/Chrono*.class
                org/pclg/tools/EmptyArrays*.class
                org/pclg/tools/FileTools*.class
                org/pclg/tools/GUITools*.class
                org/pclg/tools/ImageTools*.class
                org/pclg/tools/LabeledComponent*.class
                org/pclg/tools/ObservableProperties*.class
                org/pclg/tools/PropertiesHelper*.class
                org/pclg/tools/StringTools*.class
                org/pclg/tools/ToolBox*.class
            "/>

            <fileset dir="${img_dir}" includes="dialog-question.png"/>
            <manifest>
                <attribute name="Built-By" value="${user.name}"/>
                <attribute name="Main-Class" value="org.pclg.runtime.ProcessLauncher"/>
                <attribute name="Class-Path" value="pclg-tools.jar : log4j-api-2.13.3.jar : log4j-core-2.13.3.jar : toolbarButtonGraphics.jar : ."/>
            </manifest>
        </jar>
    </target>

    <property name="JavaShellSwing_Deprecated_jar_name" value="JavaShellSwing_Deprecated.jar"/>
    <target name="JavaShellSwing_Deprecated_jar" depends="_compile">
        <jar destfile="${dist}/${JavaShellSwing_Deprecated_jar_name}" basedir="${build}" excludes="**">
            <fileset dir="${build}" includes="
                org/pclg/runtime/JavaShellSwing_Deprecated*.class
                org/pclg/tools/EmptyArrays*.class
            	org/pclg/gui/InfoPanel*.class
            	org/pclg/log/*.class
                org/pclg/runtime/Executioner*.class
            "/>

            <fileset dir="${img_dir}" includes="dialog-question.png"/>
            <manifest>
                <attribute name="Built-By" value="${user.name}"/>
                <attribute name="Main-Class" value="org.pclg.runtime.JavaShellSwing_Deprecated"/>
                <attribute name="Class-Path" value="pclg-tools.jar : log4j-api-2.13.3.jar : log4j-core-2.13.3.jar"/>
            </manifest>
        </jar>
    </target>

    <property name="JavaShell_jar_name" value="JavaShell.jar"/>
    <target name="JavaShell_jar" depends="_compile">
        <jar destfile="${dist}/${JavaShell_jar_name}" basedir="${build}" excludes="**">
            <fileset dir="${build}" includes="
                org/pclg/runtime/JavaShell*.class
            	org/pclg/log/*.class
            "/>

            <fileset dir="${img_dir}" includes="dialog-question.png"/>
            <manifest>
                <attribute name="Built-By" value="${user.name}"/>
                <attribute name="Main-Class" value="org.pclg.runtime.JavaShell"/>
                <attribute name="Class-Path" value="pclg-tools.jar : log4j-api-2.13.3.jar : log4j-core-2.13.3.jar"/>
            </manifest>
        </jar>
    </target>

    <property name="Alles_src_zip_name" value="Alles_src.zip"/>
    <target name="Alles_src_zip" description="fuentes de la Alles">
        <jar destfile="${dist}/${Alles_src_zip_name}" basedir="${build}"
             excludes="**">
            <fileset dir="${module}" includes="src/**"/>
        </jar>
    </target>

</project>
