#Configuracion de DirectorySynchronizer
#
Application.ClassPath=derby.jar
#
#Specific to Minerva
# FIXME: este formateo parece indicar que son grupos, y no lo son
DirectorySynchronizer.cleanup.baseDirs=\
  |C:\\home\\Finance|E:\\home\\Finance|F:\\home\\Finance|L:\\home\\Finance\
  |C:\\home\\quickenw\\qdata|F:\\home\\quickenw\\qdata|L:\\quickenw\\qdata\
  |C:\\m2_repository|E:\\m2_repository\
  |C:\\home\\development\\dist|E:\\bin|L:\\bin\
  |C:\\home\\development\\modules\\src|E:\\Projects\\Alles\\src\
  |E:\\home\\development\\projects|C:\\home\\development\\projects

#Substitution variables. Use forward slash (/) instead of escaped backwards
USER_PROFILE_DIR=C:/Documents and Settings/El Coyote Cojo
LOCAL_M2_REPOSITORY_DIR=C:/m2_repository
ROOT_C=C:
ROOT_C_home=C:/home
ROOT_D=D:
ROOT_E=E:
ROOT_F=F:
ROOT_H=H:
ROOT_L=L:

#Specific to ACME
# FIXME: este formateo parece indicar que son grupos, y no lo son
#DirectorySynchronizer.cleanup.baseDirs=\
#  |/home/pablo/Finance|/media/pablo/MERCURIO/home/Finance|/media/pablo/Fatman/home/Finance|/media/pablo/UBUNTU 18_0/home/Finance\
#  |/home/pablo/quickenw/qdata|/media/pablo/Fatman/home/quickenw/qdata|/media/pablo/UBUNTU 18_0/quickenw/qdata\
#  |/home/pablo/m2_repository|/media/pablo/MERCURIO/m2_repository\
#  |/home/pablo/development/dist|/media/pablo/MERCURIO/bin|/media/pablo/UBUNTU 18_0/bin\
#  |/home/pablo/development/modules/src|/media/pablo/MERCURIO/Projects/Alles/src\
#  |/media/pablo/MERCURIO/projects_quarantine|/home/pablo/development/projects_quarantine\
#  |/media/pablo/MERCURIO/home/development/projects|/home/pablo/development/projects

#Substitution variables. Use forward slash (/) instead of escaped backwards
#USER_PROFILE_DIR=/home/pablo
#LOCAL_M2_REPOSITORY_DIR=/home/m2_repository
#ROOT_C=/
#ROOT_C_home=/home/pablo
#ROOT_D=/media/pablo/FD71-883A
#ROOT_E=/media/pablo/MERCURIO
#ROOT_F=/media/pablo/Fatman
#ROOT_H=/media/pablo/3F46-07E3
#ROOT_L=/media/pablo/UBUNTU 18_0

DirectorySynchronizer.showKaleidoscope=false
