com.lipstikLF.LipstikLookAndFeel=LipstikLookAndFeel
net.infonode.gui.laf.InfoNodeLookAndFeel=InfoNodeLookAndFeel
net.sourceforge.mlf.metouia.MetouiaLookAndFeel=MetouiaLookAndFeel
net.sourceforge.napkinlaf.NapkinLookAndFeel=NapkinLookAndFeel
com.l2fprod.gui.plaf.skinSkinLookAndFeel=SkinLookAndFeel