ProcessLauncher.title = Mensajes de ProcessLauncher

PasswordDialog.pwd.prompt     = Don't Panic
PasswordDialog.alert.capsLock = Bloquear may\u00FAsculas activado

InfoPanel.enciphering = Cifrando
InfoPanel.deciphering = Descifrando
ProcessLauncher.file.not.found = Die Datei >> {0} << existiert nicht\!